Write a C++ function `float ran1(int* idum)` that implements the Numerical Recipes ran1 random number generator. The function must maintain its own internal static state for the three linear congruential generators and the shuffling table, and it must correctly handle initialization when `*idum` is negative (seeding) or on the first call. The function should return a uniformly distributed float in the interval [0,1). It must not call any global random functions, and it must be thread-unsafe by design (static state). The seed value `*idum` should be set to 1 after initialization, and subsequent calls with `*idum` set to any non-negative value should continue the sequence without reinitializing. Handle the edge case where the shuffle index calculation could produce a value outside [1,97] by printing an error to `std::cerr` and exiting with code 1, as in the original snippet.

The algorithm follows the classic ran1 design: it uses three linear congruential generators (LCGs) with specific parameters M1/IA1/IC1, M2/IA2/IC2, M3/IA3/IC3. On initialization (first call or negative seed), it seeds ix1, ix2, ix3 from the given negative seed using modular arithmetic, then fills a 97-element shuffling table `r[1..97]` with values generated by combining ix1 and ix2. For each subsequent call, it advances all three LCGs, computes an index `j` from ix3 in the range [1,97], selects the current value from the table, replaces that table slot with a fresh combination of ix1 and ix2, and returns the selected value. Edge cases: the seed `*idum` must not be 0 (though the original doesn't check, we follow the snippet's logic; if 0 is passed, the modulo operations still work but produce predictable results). The index calculation `1 + ((97*ix3)/M3)` is guaranteed to be in [1,97] because ix3 is in [0,M3-1]; however, we keep the defensive check as in the original. Time complexity is O(1) per call after initialization, and initialization is O(97) time. Space is O(97) static. The function is deterministic given the same seed sequence.

#include <cstdlib>
#include <iostream>

// Constants as in Numerical Recipes ran1
#define M1 259200
#define IA1 7141
#define IC1 54773
#define RM1 (1.0/M1)
#define M2 134456
#define IA2 8121
#define IC2 28411
#define RM2 (1.0/M2)
#define M3 243000
#define IA3 4561
#define IC3 51349

// ran1: returns a uniform float in [0,1). Initialize with *idum < 0.
float ran1(int* idum) {
    static long ix1, ix2, ix3;
    static float r[98]; // indices 1..97 used
    float temp;
    static int iff = 0;
    int j;

    if (*idum < 0 || iff == 0) {
        iff = 1;
        ix1 = (IC1 - (*idum)) % M1;
        ix1 = (IA1 * ix1 + IC1) % M1;
        ix2 = ix1 % M2;
        ix1 = (IA1 * ix1 + IC1) % M1;
        ix3 = ix1 % M3;
        for (j = 1; j <= 97; j++) {
            ix1 = (IA1 * ix1 + IC1) % M1;
            ix2 = (IA2 * ix2 + IC2) % M2;
            r[j] = (ix1 + ix2 * RM2) * RM1;
        }
        *idum = 1; // mark as initialized
    }
    ix1 = (IA1 * ix1 + IC1) % M1;
    ix2 = (IA2 * ix2 + IC2) % M2;
    ix3 = (IA3 * ix3 + IC3) % M3;
    j = 1 + ((97 * ix3) / M3);
    if (j > 97 || j < 1) {
        std::cerr << "RAN1: This cannot happen. j = " << j << std::endl;
        std::exit(1);
    }
    temp = r[j];
    r[j] = (ix1 + ix2 * RM2) * RM1;
    return temp;
}

#undef M1
#undef IA1
#undef IC1
#undef RM1
#undef M2
#undef IA2
#undef IC2
#undef RM2
#undef M3
#undef IA3
#undef IC3

#include <cassert>
#include <cmath>
#include <cstdlib>

// Declaration of the function (since it's defined above, but in a real test we include the header)
float ran1(int* idum);

int main() {
    int seed = -1;
    // First call initializes. Verify first value matches known good.
    float a = ran1(&seed);
    // Basic sanity: value must be in [0,1)
    assert(a >= 0.0f && a < 1.0f);
    // Seed should be set to 1 after initialization
    assert(seed == 1);

    // Generate a sequence of 10 values and check they are all in range
    float vals[10];
    vals[0] = a;
    for (int i = 1; i < 10; i++) {
        vals[i] = ran1(&seed);
        assert(vals[i] >= 0.0f && vals[i] < 1.0f);
        // Check not all identical (probabilistic, but highly unlikely with good generator)
        assert(vals[i] != vals[i-1]);
    }

    // Reset with a different seed and check that sequence differs
    int seed2 = -42;
    float first2 = ran1(&seed2);
    assert(first2 != a); // with overwhelming probability
    assert(seed2 == 1);

    // Continue the same seed2 sequence and ensure it matches the previous seed2 first call
    (void)ran1(&seed2);
    float third2 = ran1(&seed2);
    // Since we only called twice after init, the third call should be different from first2
    assert(third2 != first2);

    // Check reproducibility: reinitialize seed -1 again and get same first number
    int seed3 = -1;
    float first3 = ran1(&seed3);
    assert(first3 == a); // exact same because algorithm is deterministic

    // Check the entire sequence of 97 values doesn't hit the error branch (implicit)
    int seed4 = -12345;
    for (int i = 0; i < 1000; i++) {
        float v = ran1(&seed4);
        assert(v >= 0.0f && v < 1.0f);
    }

    // Test that the shuffle table works: generate 200 values and check they're all distinct? Not necessary, but test min/max spread
    float minv = 1.0f, maxv = 0.0f;
    for (int i = 0; i < 10000; i++) {
        float v = ran1(&seed4);
        if (v < minv) minv = v;
        if (v > maxv) maxv = v;
    }
    // With 10000 samples, min should be near 0 and max near 1 (but not exactly)
    assert(minv < 0.01f);
    assert(maxv > 0.99f);

    return 0;
}
