// Write a C++ function `int sumSpiralLayer(int n, int layer)` that takes a positive integer `n` and a non-negative integer `layer` as input. The function should compute the sum of all numbers that appear in the specified `layer` (0-indexed from the outermost layer) of the "spiral diamond" pattern generated by the function `pattern23` from the reference code. The pattern for a given `n` is an `(2*n - 1)` by `(2*n - 1)` grid, where each cell contains the value `n - min(row, col)`, where `row` and `col` are 0-indexed. A "layer" is defined as all cells at a minimum distance from the border, where layer 0 is the outermost border (all cells where either row is 0, row is `2*n-2`, col is 0, or col is `2*n-2`), and layer 1 is the next inner square of cells (where row and col are between 1 and `2*n-3` and at least one is at distance 1 from the border), and so on. The function should return the sum of all distinct cell values in that layer. For clarity, if `layer` is invalid (i.e., `layer < 0` or `layer >= n`), the function should return 0. The function must be self-contained and not rely on any global state.

#include <cassert>

int sumSpiralLayer(int, int); // declaration

int main() {
    // n=1: single cell value 1, layer 0 sum = 1
    assert(sumSpiralLayer(1, 0) == 1);
    // n=2, side=3. Layer 0: outer ring (all 8 cells) value = n - 0 = 2, sum = 8*2=16
    assert(sumSpiralLayer(2, 0) == 16);
    // n=2, layer 1: center cell value = 1, sum = 1
    assert(sumSpiralLayer(2, 1) == 1);
    // n=3, side=5. Layer 0: ring of 16 cells, value=3, sum=48
    assert(sumSpiralLayer(3, 0) == 48);
    // n=3, layer 1: ring of 8 cells, value=2, sum=16
    assert(sumSpiralLayer(3, 1) == 16);
    // n=3, layer 2: center cell value=1, sum=1
    assert(sumSpiralLayer(3, 2) == 1);
    // n=4, side=7. Layer 0: 24 cells value=4 -> 96
    assert(sumSpiralLayer(4, 0) == 96);
    // n=4, layer 1: 16 cells value=3 -> 48
    assert(sumSpiralLayer(4, 1) == 48);
    // n=4, layer 2: 8 cells value=2 -> 16
    assert(sumSpiralLayer(4, 2) == 16);
    // n=4, layer 3: 1 cell value=1 -> 1
    assert(sumSpiralLayer(4, 3) == 1);
    // Invalid layer
    assert(sumSpiralLayer(3, 3) == 0);
    assert(sumSpiralLayer(3, -1) == 0);
    // n=0 (though not positive, just defensive)
    assert(sumSpiralLayer(0, 0) == 0);
    return 0;
}

#include <algorithm>

// Sum the values in a given spiral layer (0 = outermost) of the pattern.
// layer must be between 0 and n-1; otherwise returns 0.
int sumSpiralLayer(int n, int layer) {
    if (n <= 0 || layer < 0 || layer >= n) {
        return 0;
    }
    const int side = 2 * n - 1;
    const int s = side - 2 * layer;  // side length of this layer's square
    const int cellCount = (s == 1) ? 1 : (4 * s - 4);
    const int value = n - layer;
    return value * cellCount;
}

// The pattern from `pattern23` produces a diamond-like square matrix of side length `side = 2*n - 1`, where each cell value is determined by `n - min(i, j)` where `i` and `j` are row and column indices from 0 to `side-1`. The value at any cell depends only on the minimum distance to the nearest border, i.e., `distance = min(i, j, side-1-i, side-1-j)`. This distance ranges from 0 (outer border) to `n-1` (center cell(s)). A layer `L` corresponds to all cells where this distance equals `L`. Since the matrix is symmetric, the sum of all cells in a given layer can be computed by summing over rows from `L` to `side-1-L`, and for each row, summing cells in that row that belong to the layer (columns from `L` to `side-1-L`). However, because the value is constant on each "ring", we can derive a formula: For a fixed distance `d`, the ring consists of 4 sides of length `(side - 2*d)` minus the 4 corners counted twice? Actually, the ring is a square outline of side length `side - 2*d`. Number of cells in that outline is `4*(side - 2*d - 1)` if `side - 2*d > 1`, and 1 if it equals 1. But note the value on each cell of that ring is exactly `n - d` because the minimum distance to border equals `d`. So the sum for layer `d` is simply `(n - d) * cellCount`, where `cellCount` is the number of cells in that layer. The cellCount for a ring at distance `d` is: if `side - 2*d == 1`, then 1; otherwise `4*(side - 2*d) - 4`? Let's be precise: A square outline of side length `s` (where `s = side - 2*d`) has `4*s - 4` cells if `s > 1`, and 1 if `s == 1`. Since `side = 2*n - 1`, for a given layer `d`, `s = (2*n - 1) - 2*d`. The value is `n - d`. So sum = `(n - d) * ( (s > 1) ? (4*s - 4) : 1 )`. Edge cases: If `layer >= n` or negative, return 0 (since `d` ranges 0 to `n-1`). Complexity: O(1) time and O(1) space. Note that the function should handle `n=0`? The problem says positive integer `n`, so `n >= 1`. For `n=1`, side=1, only layer 0 with one cell value 1, sum=1. The formula works.
