Write a C++ function `printAllSubarraySums` that takes a `const std::vector<int>&` and returns a `std::string` containing all sums of every contiguous subarray, in the order they would be generated by the nested loops shown in the snippet (outer loop from index 0 to n-1, inner loop from i to n-1). Each sum should be followed by a single space, except no trailing space after the last sum. If the input is empty, return an empty string. For example, for `{1, 2, 3}`, the output should be `"1 3 6 2 5 3 "` but without the trailing space: `"1 3 6 2 5 3"`. Handle negative numbers, zeros, and large values (up to 10^9) correctly.
#include <cassert>
#include <vector>
#include <string>

// Include the solution function declaration here (or link it)
std::string printAllSubarraySums(const std::vector<int>& nums);

int main() {
    assert(printAllSubarraySums({}) == "");
    assert(printAllSubarraySums({1}) == "1");
    assert(printAllSubarraySums({1, 2, 3}) == "1 3 6 2 5 3");
    assert(printAllSubarraySums({-1, -2}) == "-1 -3 -2");
    assert(printAllSubarraySums({0, 5, -2}) == "0 5 3 5 3 -2");
    assert(printAllSubarraySums({1000000000, 1000000000}) == "1000000000 2000000000 1000000000");
    assert(printAllSubarraySums({4, -1, 2}) == "4 3 5 -1 1 2");
    return 0;
}
#include <string>
#include <vector>
#include <sstream>

// Returns a string with all subarray sums of nums, space-separated, no trailing space.
std::string printAllSubarraySums(const std::vector<int>& nums) {
    std::ostringstream output;
    const size_t n = nums.size();

    for (size_t i = 0; i < n; ++i) {
        long long sum = 0;  // Use long long to avoid overflow for large values
        for (size_t j = i; j < n; ++j) {
            sum += nums[j];
            output << sum << ' ';
        }
    }

    std::string result = output.str();
    // Remove trailing space if there is one
    if (!result.empty()) {
        result.pop_back();
    }
    return result;
}
// The task is to compute the sum of every contiguous subarray of the input vector and collect them in a single string. The brute-force approach is to use two nested loops: an outer loop over starting index `i` from 0 to n-1, and an inner loop over ending index `j` from i to n-1, accumulating the sum incrementally. This matches the given snippet exactly. The key is to build the result string efficiently to avoid repeated concatenation overhead—use `std::ostringstream` to append each sum followed by a space, then remove the trailing space at the end (or check if the stream is empty). Edge cases: empty vector returns empty string; a vector of size 1 yields a single sum; negative numbers and zeros work naturally. Time complexity is O(n²) because there are n(n+1)/2 subarrays, and each subarray sum is computed incrementally in O(1) per step. Space complexity is O(n²) for the output string (since we store all sums), but auxiliary space beyond that is O(1). The solution must be `const`-correct and use a descriptive function name.
