// Given an integer `n` (where 1 ≤ n ≤ 14), write a C++ function `vector<vector<int>> nQueensSolutions(int n)` that returns the first up to 3 distinct solutions to the classic N-Queens problem, where you place `n` queens on an `n × n` chessboard such that no two queens attack each other (no two share the same row, column, or diagonal). The function should output a vector of solutions, where each solution is a vector of length `n` (index 1..n) giving the column position (1-based) of the queen in each row. Additionally, the function must return a count of all valid solutions, but since returning both a count and the first 3 solutions is awkward in a single return type, design the function to return `vector<vector<int>>` containing at most 3 solutions, and use a reference parameter `int& totalSolutions` to output the total number of valid solutions. The returned solutions should be in lexicographic order of their row-wise column placements (as generated by a standard backtracking search). If there are fewer than 3 solutions, return all of them in order. If `n` is invalid (e.g., less than 1), return an empty vector and set `totalSolutions` to 0.

#include <cassert>
#include <vector>

// The solution function is declared above.
// Testing the nQueensSolutions function.

int main() {
    int total = 0;

    // n = 1: one solution [1]
    auto sol1 = nQueensSolutions(1, total);
    assert(total == 1);
    assert(sol1.size() == 1);
    assert(sol1[0][0] == 1);

    // n = 2: no solutions
    auto sol2 = nQueensSolutions(2, total);
    assert(total == 0);
    assert(sol2.empty());

    // n = 3: no solutions
    auto sol3 = nQueensSolutions(3, total);
    assert(total == 0);
    assert(sol3.empty());

    // n = 4: exactly 2 solutions. Expected lexicographic order:
    // [2,4,1,3] and [3,1,4,2]
    auto sol4 = nQueensSolutions(4, total);
    assert(total == 2);
    assert(sol4.size() == 2);
    assert(sol4[0][0] == 2 && sol4[0][1] == 4 && sol4[0][2] == 1 && sol4[0][3] == 3);
    assert(sol4[1][0] == 3 && sol4[1][1] == 1 && sol4[1][2] == 4 && sol4[1][3] == 2);

    // n = 5: total = 10, first 3 solutions:
    // [1,3,5,2,4], [1,4,2,5,3], [2,4,1,3,5]
    auto sol5 = nQueensSolutions(5, total);
    assert(total == 10);
    assert(sol5.size() == 3);
    assert(sol5[0][0] == 1 && sol5[0][1] == 3 && sol5[0][2] == 5 && sol5[0][3] == 2 && sol5[0][4] == 4);
    assert(sol5[1][0] == 1 && sol5[1][1] == 4 && sol5[1][2] == 2 && sol5[1][3] == 5 && sol5[1][4] == 3);
    assert(sol5[2][0] == 2 && sol5[2][1] == 4 && sol5[2][2] == 1 && sol5[2][3] == 3 && sol5[2][4] == 5);

    // n = 0: invalid, empty result
    auto sol0 = nQueensSolutions(0, total);
    assert(total == 0);
    assert(sol0.empty());

    // n = 8: total = 92, but only first 3 returned
    auto sol8 = nQueensSolutions(8, total);
    assert(total == 92);
    assert(sol8.size() == 3);

    // n = 14: total = 365596, but only first 3 returned (just check size and total)
    auto sol14 = nQueensSolutions(14, total);
    assert(total == 365596);
    assert(sol14.size() == 3);

    return 0;
}

#include <vector>
#include <cstring>

// Backtracking helper for N-Queens.
// Returns the first up to 3 solutions in lexicographic order.
// totalSolutions is set to the total number of valid placements.
std::vector<std::vector<int>> nQueensSolutions(int n, int& totalSolutions) {
    totalSolutions = 0;
    std::vector<std::vector<int>> result;
    if (n < 1) return result;

    // placement[r] = column of queen in row r (1-based), for r in [1..n]
    std::vector<int> placement(n + 1, 0);
    // Attack sets: colUsed[c], diagUsed[main: (row-col)+n], antiDiagUsed[(row+col)]
    std::vector<bool> colUsed(n + 1, false);
    std::vector<bool> diagUsed(2 * n + 1, false);   // index = row - col + n
    std::vector<bool> antiDiagUsed(2 * n + 1, false); // index = row + col

    // Recursive lambda defined via std::function, but we can use a helper function with captures.
    // For simplicity, use a local recursive function pointer via std::function.
    // However, to avoid heavy std::function, we use a nested lambda with a self-capture pattern (C++14).
    auto backtrack = [&](auto&& self, int row) -> void {
        if (row > n) {
            ++totalSolutions;
            if (result.size() < 3) {
                result.emplace_back(placement.begin() + 1, placement.end());
            }
            return;
        }

        for (int col = 1; col <= n; ++col) {
            int diag = row - col + n;
            int anti = row + col;
            if (colUsed[col] || diagUsed[diag] || antiDiagUsed[anti]) {
                continue;
            }

            placement[row] = col;
            colUsed[col] = true;
            diagUsed[diag] = true;
            antiDiagUsed[anti] = true;

            self(self, row + 1);

            // Backtrack
            colUsed[col] = false;
            diagUsed[diag] = false;
            antiDiagUsed[anti] = false;
            placement[row] = 0;
        }
    };

    backtrack(backtrack, 1);
    return result;
}

// The problem is the classic N-Queens. We use backtracking: place a queen row by row, starting from row 1, and for each row, try each column from 1 to n. Before placing, we check whether the column and both diagonals are already attacked by previously placed queens. We can maintain three arrays or sets: one for columns, one for the main diagonal (row-col index), and one for the anti-diagonal (row+col index). To generate solutions in lexicographic order, simply iterate columns from 1 to n. When a full solution is found (row > n), increment the total count, and if the count is less than or equal to 3, store a copy of the current placement. Time complexity is O(n!) in the worst case due to the number of placements, but pruning reduces this; for n ≤ 14 it is acceptable. Space complexity is O(n) for the placement array and O(n) for the attack sets, plus O(3n) for storing up to 3 solutions, so overall O(n) auxiliary space. Edge cases: n = 1 returns one solution `[1]`; n = 0 or negative returns empty. For n = 2,3 there are no solutions, so totalSolutions = 0 and the returned vector is empty.
