Write a C++ function `nQueensSolutions(int n)` that returns all distinct solutions to the N-Queens puzzle for an `n x n` chessboard, where each solution is represented as a vector of integers of length `n`. The integer at position `i` (0-indexed) denotes the row number (1-indexed) where the queen is placed in column `i`. The function should return a vector of all such valid configurations, sorted in increasing lexicographic order of the integer sequences (as the natural order generated by scanning rows from top to bottom for each column). For example, for `n = 4`, there are two solutions: `{2, 4, 1, 3}` and `{3, 1, 4, 2}`. If no solution exists, return an empty vector. The function must handle `n` from 1 to 9 inclusively. The time complexity should be optimized with a backtracking approach that checks attack conditions efficiently.
#include <cassert>
#include <vector>

// The solution function is declared here (or included above).
// This main function provides runnable checks.

int main() {
    // n=1: one solution
    std::vector<std::vector<int>> sol1 = nQueensSolutions(1);
    assert(sol1.size() == 1);
    assert(sol1[0] == std::vector<int>({1}));

    // n=2 and n=3 have no solutions
    assert(nQueensSolutions(2).empty());
    assert(nQueensSolutions(3).empty());

    // n=4: exactly two known solutions
    std::vector<std::vector<int>> sol4 = nQueensSolutions(4);
    assert(sol4.size() == 2);
    assert(sol4[0] == std::vector<int>({2, 4, 1, 3}));
    assert(sol4[1] == std::vector<int>({3, 1, 4, 2}));

    // n=8: known number of solutions is 92
    assert(nQueensSolutions(8).size() == 92);

    // n=9: known number of solutions is 352
    assert(nQueensSolutions(9).size() == 352);

    // Verify that each solution for n=5 is valid and unique
    std::vector<std::vector<int>> sol5 = nQueensSolutions(5);
    assert(sol5.size() == 10); // known count for n=5
    for (const auto& sol : sol5) {
        assert(sol.size() == 5);
        // Check no two queens share a row (rows are 1..5 distinct)
        std::vector<bool> rowsSeen(6, false);
        for (int r : sol) { assert(r >= 1 && r <= 5); assert(!rowsSeen[r]); rowsSeen[r] = true; }
        // Check no diagonal conflicts
        for (int i = 0; i < 5; ++i) {
            for (int j = i+1; j < 5; ++j) {
                assert(abs(sol[i] - sol[j]) != abs(i - j));
            }
        }
    }

    // For n=4, also confirm lexicographic order
    assert(sol4[0] < sol4[1]);

    return 0;
}
#include <vector>
#include <string>

// Returns all distinct solutions to the N-Queens problem.
// Each solution is a vector of length n, where solution[col] gives the row (1-indexed) of the queen in that column.
// Solutions are returned in lexicographic order of the row sequences.
std::vector<std::vector<int>> nQueensSolutions(int n) {
    std::vector<std::vector<int>> solutions;
    std::vector<int> current(n, 0);          // current[col] = row (0-indexed during search)
    std::vector<bool> rowUsed(n, false);
    std::vector<bool> diag1Used(2 * n - 1, false); // main diagonal index = row - col + n - 1
    std::vector<bool> diag2Used(2 * n - 1, false); // anti-diagonal index = row + col

    // Backtracking helper.
    auto backtrack = [&](int col, auto&& self) -> void {
        if (col == n) {
            // Convert 0-indexed rows to 1-indexed and record.
            std::vector<int> sol;
            sol.reserve(n);
            for (int r : current) {
                sol.push_back(r + 1);
            }
            solutions.push_back(sol);
            return;
        }

        for (int row = 0; row < n; ++row) {
            int d1 = row - col + n - 1;
            int d2 = row + col;
            if (!rowUsed[row] && !diag1Used[d1] && !diag2Used[d2]) {
                current[col] = row;
                rowUsed[row] = true;
                diag1Used[d1] = true;
                diag2Used[d2] = true;

                self(col + 1, self);

                // Backtrack.
                rowUsed[row] = false;
                diag1Used[d1] = false;
                diag2Used[d2] = false;
            }
        }
    };

    backtrack(0, backtrack);
    return solutions;
}
// The problem is a classic backtracking search. We place queens column by column from left to right. For each column, we try every row, but only if it does not conflict with previously placed queens. A queen attacks if it is in the same row, same main diagonal (difference `row - col` constant), or same anti-diagonal (sum `row + col` constant). Instead of checking all previous queens each time, we can maintain three boolean arrays: one for used rows, one for occupied main diagonals (index `row - col + n - 1` to make non-negative), and one for occupied anti-diagonals (index `row + col`). This reduces the safety check to O(1). We recursively place queens for columns `0` to `n-1`. When a full placement is made, we record the 1-indexed rows in the order of columns. The backtracking naturally explores rows in increasing order per column, which yields lexicographically sorted results when we collect them in order. Edge cases: for `n=1`, solutions is `{{1}}`; for `n=2` and `n=3`, no solutions; for `n=4`, exactly two solutions. The time complexity is O(n!) in the worst case, but the pruning makes it much faster in practice; the space complexity is O(n) for the temporary storage and O(n) for the three marker arrays, plus O(T) for the result where T is the number of solutions.
