// You are given an integer `n` and a grid of size `n` rows by `n-1` columns, containing a permutation of the integers from 1 to `n` (each appears exactly once overall). This grid is formed by taking the original permutation and, for each position `i` from 1 to `n`, removing the element at index `i` (0-indexed) from the permutation, leaving the other `n-1` elements in their original relative order. The rows are provided in some arbitrary order. Write a C++ function that reconstructs and returns the original permutation of size `n` as a `std::vector<int>`. The input is given as a 2D vector `grid` where `grid.size() == n` and each `grid[i].size() == n-1`. You may assume the input is always valid according to the generation process. The function must run efficiently for `n` up to 100.
// The key observation is that in every row, exactly one element from the original permutation is missing. Since the original permutation contains all numbers from 1 to `n`, the first element of each row is either the first element of the original permutation or the second element (if the first element was removed from that row). To find the original first element, compare the first elements of all rows. The value that appears most frequently among `grid[i][0]` is the correct first element of the permutation. Specifically, if all rows have the same first element except one row that differs, the majority (n-1 rows) share the true first element, and the single differing row is the one where the first element was removed. After determining the true first element, find the row that has a different first element; that row is missing the first element, so it contains the rest of the original permutation in order. If no row differs (i.e., all first elements are equal), then the row that was missing the first element must have been the one where the first element was removed from the permutation—but wait, if all first elements are equal, that means no row has a different first element, which cannot happen for n>1 because the row where the first element was removed would start with the second element. However, if n==2, the grid has 2 rows and 1 column; then both rows contain a single number, and one row contains `[first]` and the other contains `[second]`, so the majority is not possible. But the problem guarantees a valid input, so we handle the general approach: count occurrences of first elements. The one that appears `n-1` times is the true first element, and the unique row that differs (if any) gives the rest. If all first elements are identical (which only happens when n==1, but n>=2 per constraints), then the first element is that value and we need to find the row that starts with the second element—but since all rows start with the same value, that cannot happen for n>=2. In practice, we can always find a row whose first element differs from the majority, and that row gives the tail. Algorithm: (1) Count frequency of each `grid[i][0]` using a map. (2) Identify the value with frequency `n-1` (the true first element). (3) Find the row `r` where `grid[r][0] != firstElement`. If no such row exists (edge case), then find any row and use it? But logically it must exist for n>=2. For safety, if no differing row is found, use the first row as the tail (but this would be incorrect; however, constraints guarantee correctness). (4) Construct answer as `[firstElement] + grid[r]` (all elements of that row). Time complexity: O(n^2) to scan the grid, but we only need to check first elements and then copy one row, so O(n) for scanning plus O(n) for copying, but reading the grid is O(n^2) anyway. Space: O(n) for the answer and O(n) for a map. The solution is simple and robust.
#include <vector>
#include <map>
#include <algorithm>

// Reconstruct the original permutation from the given grid of size n x (n-1).
// The grid is generated by removing one element from the permutation per row.
std::vector<int> reconstructPermutation(const std::vector<std::vector<int>>& grid) {
    int n = static_cast<int>(grid.size());
    if (n == 0) return {};

    // Count frequencies of the first element in each row.
    std::map<int, int> firstCount;
    for (const auto& row : grid) {
        if (!row.empty()) {
            ++firstCount[row[0]];
        }
    }

    // The true first element appears n-1 times (all rows except the one missing it).
    int firstElement = -1;
    for (const auto& [value, count] : firstCount) {
        if (count == n - 1) {
            firstElement = value;
            break;
        }
    }

    // Find a row whose first element differs from the true first element.
    // That row contains the remaining elements in order.
    const std::vector<int>* tailRow = nullptr;
    for (const auto& row : grid) {
        if (!row.empty() && row[0] != firstElement) {
            tailRow = &row;
            break;
        }
    }

    // If no differing row was found (should not happen for valid input with n>=2),
    // fallback: use the first row as the tail (but this is not expected).
    if (tailRow == nullptr) {
        tailRow = &grid.front();
    }

    // Build the answer: firstElement followed by all elements of the tail row.
    std::vector<int> result;
    result.reserve(n);
    result.push_back(firstElement);
    result.insert(result.end(), tailRow->begin(), tailRow->end());

    return result;
}
#include <cassert>
#include <vector>

int main() {
    // Example from the original problem (n=4, permutation [1,2,3,4])
    std::vector<std::vector<int>> grid1 = {
        {2, 3, 4},
        {1, 3, 4},
        {1, 2, 4},
        {1, 2, 3}
    };
    std::vector<int> ans1 = reconstructPermutation(grid1);
    std::vector<int> expected1 = {1, 2, 3, 4};
    assert(ans1 == expected1);

    // Another example: permutation [3,1,2] (n=3)
    std::vector<std::vector<int>> grid2 = {
        {3, 2},
        {3, 1},
        {1, 2}
    };
    std::vector<int> ans2 = reconstructPermutation(grid2);
    std::vector<int> expected2 = {3, 1, 2};
    assert(ans2 == expected2);

    // n=2: permutation [5,9]
    std::vector<std::vector<int>> grid3 = {
        {5},
        {9}
    };
    std::vector<int> ans3 = reconstructPermutation(grid3);
    std::vector<int> expected3 = {5, 9};
    assert(ans3 == expected3);

    // n=5: permutation [7,3,8,1,4]
    std::vector<std::vector<int>> grid4 = {
        {7, 8, 1, 4},
        {7, 3, 1, 4},
        {7, 3, 8, 4},
        {7, 3, 8, 1},
        {3, 8, 1, 4}
    };
    std::vector<int> ans4 = reconstructPermutation(grid4);
    std::vector<int> expected4 = {7, 3, 8, 1, 4};
    assert(ans4 == expected4);

    // Edge: n=1 (not typical but test for robustness)
    std::vector<std::vector<int>> grid5 = {{}}; // n-1 = 0, so each row is empty? Invalid but handle gracefully
    // Since n=1, grid is 1x0, reconstruct should return {0}? But constraints say n>=2, skip.

    return 0;
}
