// Write a C++ function `vector<vector<int>> allPermutations(vector<int>& nums)` that generates and returns all permutations of the input vector `nums`. The function must not include the original order requirement — it can generate permutations in any order, but must include every distinct permutation exactly once. The input vector may contain duplicate elements, but your function should treat each element as distinct (i.e., if the input contains duplicate values, the permutations that differ only by swapping identical values are considered distinct). The function must handle an empty input vector by returning a vector containing one empty vector (a single empty permutation). The solution must use a recursive backtracking approach, modifying the input in‑place during recursion and restoring it after each recursive call. The returned vector of vectors must not share memory with the input vector (i.e., each permutation must be a separate copy). The function must be declared as a free function (not a member of a class).

#include <cassert>
#include <vector>
#include <algorithm>

int main() {
    // Test 1: Empty input → one empty permutation
    std::vector<int> empty;
    auto permsEmpty = allPermutations(empty);
    assert(permsEmpty.size() == 1);
    assert(permsEmpty[0].empty());
    assert(empty.empty()); // input unchanged

    // Test 2: Single element
    std::vector<int> single = {5};
    auto permsSingle = allPermutations(single);
    assert(permsSingle.size() == 1);
    assert(permsSingle[0] == std::vector<int>({5}));
    assert(single == std::vector<int>({5})); // unchanged

    // Test 3: Three distinct elements → 6 permutations
    std::vector<int> nums = {1, 2, 3};
    auto perms = allPermutations(nums);
    assert(perms.size() == 6);
    // Check that all permutations are unique and contain all elements
    std::vector<std::vector<int>> expected = {
        {1,2,3}, {1,3,2}, {2,1,3}, {2,3,1}, {3,1,2}, {3,2,1}
    };
    for (const auto& p : perms) {
        assert(std::find(expected.begin(), expected.end(), p) != expected.end());
    }
    // Check input unchanged
    assert(nums == std::vector<int>({1, 2, 3}));

    // Test 4: Duplicate values – treat positions as distinct → still 6 permutations for three identical? 
    // Actually for {1,1,2}, with positions distinct, we get 3! = 6 permutations (some duplicate values but distinct orders).
    std::vector<int> dup = {1, 1, 2};
    auto permsDup = allPermutations(dup);
    assert(permsDup.size() == 6);
    // Check that each permutation has size 3 and contains exactly two 1's and one 2
    for (const auto& p : permsDup) {
        assert(p.size() == 3);
        int count1 = 0, count2 = 0;
        for (int x : p) {
            if (x == 1) ++count1;
            if (x == 2) ++count2;
        }
        assert(count1 == 2 && count2 == 1);
    }
    // Ensure all 6 are distinct (by position they are distinct, but values may repeat)
    // Since values have duplicates, we can still check that no two are identical as vectors (they should be distinct because generated by swaps)
    for (size_t i = 0; i < permsDup.size(); ++i) {
        for (size_t j = i + 1; j < permsDup.size(); ++j) {
            assert(permsDup[i] != permsDup[j]); // they are all distinct vectors
        }
    }
    // Input unchanged
    assert(dup == std::vector<int>({1, 1, 2}));

    // Test 5: Two elements
    std::vector<int> two = {7, 8};
    auto permsTwo = allPermutations(two);
    assert(permsTwo.size() == 2);
    assert(permsTwo[0] == std::vector<int>({7,8}) || permsTwo[0] == std::vector<int>({8,7}));
    assert(permsTwo[1] == std::vector<int>({7,8}) || permsTwo[1] == std::vector<int>({8,7}));
    assert(permsTwo[0] != permsTwo[1]);

    return 0;
}

#include <vector>

// Generate all permutations of the input vector nums.
// Each permutation is stored as a separate copy in the returned vector.
// The input nums is modified temporarily but restored to its original state.
std::vector<std::vector<int>> allPermutations(std::vector<int>& nums) {
    std::vector<std::vector<int>> result;
    
    // Recursive helper (lambda not used for simplicity; internal function)
    // Define a recursive DFS function.
    std::function<void(int)> dfs = [&](int begin) {
        if (begin >= static_cast<int>(nums.size())) {
            result.push_back(nums);  // copy of current permutation
            return;
        }
        for (int i = begin; i < static_cast<int>(nums.size()); ++i) {
            std::swap(nums[begin], nums[i]);
            dfs(begin + 1);
            std::swap(nums[begin], nums[i]); // backtrack
        }
    };
    
    dfs(0);
    return result;
}

// The core idea is a depth‑first search (DFS) that builds permutations by fixing one element at a time at the current position. Starting from index `begin`, for each index `i` from `begin` to `size−1`, we swap the element at `begin` with the element at `i`, recurse with `begin+1`, and then swap back to restore the original order for the next iteration. When `begin` reaches `size`, the current vector is a complete permutation, so we push a copy onto the result. This classic swap‑based backtracking ensures all permutations are generated. Edge cases: (1) empty input – the base case triggers immediately with `begin==size==0` and pushes an empty vector; (2) single element – no swaps needed, one permutation returned; (3) duplicate values – since we treat elements as distinct by their positions, we do not skip duplicates, and the algorithm naturally generates all permutations (including those that look identical if values repeat, but they are distinct by index). Time complexity: O(n!) permutations, each generated in O(n) time to copy, so total O(n·n!). Space complexity: O(n) for recursion stack, plus O(n·n!) for storing all permutations in the result.
