/*
Write a C++ function that, given a positive integer `n`, returns a `std::vector<std::vector<int>>` containing all permutations of the integers `0, 1, ..., n-1` in lexicographic order. Each permutation must be represented as a vector of integers. If `n` is 0, return an empty vector (no permutations). The function should use a recursive backtracking approach with a boolean "used" array. The output permutations must be in the order generated by the recursive algorithm: for each position, try the smallest unused number first, then backtrack. Ensure the solution is self-contained, with proper `const` correctness where applicable (e.g., the function signature should accept `n` by value, and all helper arrays should be local).
*/

#include <vector>

// Generate all permutations of 0..n-1 in lexicographic order using backtracking.
std::vector<std::vector<int>> generatePermutations(int n) {
    std::vector<std::vector<int>> result;
    if (n == 0) return result; // No permutations for empty range

    std::vector<int> perm(n);
    std::vector<bool> unused(n, true); // unused[i] == true means number i is available

    // Recursive lambda to fill positions from index 0 to n-1
    // Uses 'auto&& self' for recursion within a lambda in C++14 and later.
    // For C++11 compatibility, we use a free helper function instead (see below).
    // To keep it simple, we define a private helper function outside the main function.
    // But since the task requires a free function, we implement it as a nested recursive function.
    // However, C++ does not allow nested functions in standard. So we use a recursive lambda.
    // We use a generic lambda with auto&& to allow recursion.
    auto backtrack = [&](auto&& self, int pos) -> void {
        if (pos == n) {
            result.push_back(perm);
            return;
        }
        for (int val = 0; val < n; ++val) {
            if (unused[val]) {
                perm[pos] = val;
                unused[val] = false;
                self(self, pos + 1);
                unused[val] = true; // backtrack
            }
        }
    };

    backtrack(backtrack, 0);
    return result;
}
(Note: The above uses a recursive lambda, which requires C++14 or later. For strict C++11 compatibility, one could use a static helper function inside an unnamed namespace; the logic is identical. The solution is self-contained with only `<vector>` included.)

#include <cassert>
#include <vector>

// Declare the function we are testing (or include the header if provided elsewhere)
std::vector<std::vector<int>> generatePermutations(int n);

int main() {
    // Test n=0: empty result
    assert(generatePermutations(0).empty());

    // Test n=1: single permutation [0]
    auto p1 = generatePermutations(1);
    assert(p1.size() == 1);
    assert(p1[0] == std::vector<int>{0});

    // Test n=2: permutations [0,1] and [1,0]
    auto p2 = generatePermutations(2);
    assert(p2.size() == 2);
    assert(p2[0] == std::vector<int>{0, 1});
    assert(p2[1] == std::vector<int>{1, 0});

    // Test n=3: full lexicographic order of 6 permutations
    auto p3 = generatePermutations(3);
    assert(p3.size() == 6);
    assert(p3[0] == std::vector<int>{0, 1, 2});
    assert(p3[1] == std::vector<int>{0, 2, 1});
    assert(p3[2] == std::vector<int>{1, 0, 2});
    assert(p3[3] == std::vector<int>{1, 2, 0});
    assert(p3[4] == std::vector<int>{2, 0, 1});
    assert(p3[5] == std::vector<int>{2, 1, 0});

    // Test n=4: ensure size is 24 and first/last elements are correct
    auto p4 = generatePermutations(4);
    assert(p4.size() == 24);
    assert(p4.front() == std::vector<int>{0, 1, 2, 3});
    assert(p4.back() == std::vector<int>{3, 2, 1, 0});

    return 0;
}

// The core algorithm is recursive backtracking. We maintain an array `perm` of size `n` to hold the current partial permutation, and a boolean vector `used` of size `n` where `used[i]` is `true` if integer `i` has not yet been placed. The recursive function `generate(perm, used, position, n, result)` places a number at `perm[position]` by iterating `j` from 0 to `n-1`. If `used[j]` is true, we set `perm[position] = j`, mark `used[j] = false`, and recurse to `position+1`. When `position == n-1` (i.e., we have filled the last index), we copy the entire `perm` into a vector and append to `result`. After returning from recursion, we restore `used[j] = true` (backtracking). The base case when `n == 0` returns an empty vector immediately because there are no numbers to permute. Edge cases: `n = 1` produces exactly one permutation `[0]`. The algorithm generates all `n!` permutations, each with `O(n)` copying time, so total time complexity is `O(n * n!)`, and space complexity is `O(n)` for the recursion stack and `perm`/`used` arrays, plus `O(n * n!)` for the output storage (which is unavoidable). The lexicographic order emerges naturally because we iterate `j` in increasing order at every position.
