// Write a C++ function `sumOfAccumulatingSums` that takes no parameters and returns an `int`. The function must compute and return the total sum of all partial accumulated sums generated by iterating from 1 to 100 inclusive. More precisely, initialize an accumulator `n` to 0 and a total `sum` to 0. For each integer `i` from 1 to 100, add `i` to `n`, then add the new value of `n` to `sum`. Finally, return the value of `sum`. The function must be side-effect-free (no printing, no I/O) and const-correct where applicable (the function itself can be marked `const` if it were a member, but here as a free function, use `const` for any local variables that don't change after initialization). This is a purely computational task; no input, no error handling needed. The result is a fixed integer that can be verified analytically.
#include <cassert>

int main() {
    assert(sumOfAccumulatingSums() == 171700);
    // For verification, also check smaller known values:
    // We can't easily test sub-ranges without modifying the function, but we can
    // reason: the function is fixed, so we just assert the only possible return.
    assert(sumOfAccumulatingSums() > 0);
    assert(sumOfAccumulatingSums() == sumOfAccumulatingSums()); // deterministic
}
// Compute the sum of all partial accumulated sums for i = 1..100.
// For each i, n becomes the sum of 1..i, and that value is added to the total.
int sumOfAccumulatingSums() {
    int accumulator = 0;
    int total = 0;
    for (int i = 1; i <= 100; ++i) {
        accumulator += i;
        total += accumulator;
    }
    return total;
}
// The algorithm is straightforward: simulate the described loop exactly. At step `i`, the accumulator `n` equals `1 + 2 + ... + i` (the triangular number `T_i`), and we add `T_i` to the total. So the answer is the sum of the first 100 triangular numbers: `Σ_{i=1}^{100} T_i = Σ_{i=1}^{100} i*(i+1)/2`. This sum can be computed analytically, but here we just loop. Edge cases: none, because the range is fixed and positive. Time complexity: O(100) = O(1) in the sense that it's constant; space complexity: O(1) because we only use two integer variables. The loop runs exactly 100 iterations, each doing constant work. The final result should be computed precisely; no overflow occurs because the sum of triangular numbers up to 100 is 171700 (since sum of T_i = n(n+1)(n+2)/6 for n=100 gives 100*101*102/6 = 171700). That fits comfortably in a 32-bit int.
