// Given a positive integer `base` and a positive integer `length`, write a C++ function `std::vector<double> generateRandomizedSequence(int base, int length)` that generates a sequence of `length` pseudo-random numbers in the interval `[0, 1)` using a simplified version of the Owen-scrambled digital sequence approach inspired by the provided code. Specifically, the function should simulate a one-dimensional digital sequence with a single digit per element (i.e., `NumDigits = 1`), using a random permutation of the digits `{0, 1, ..., base-1}` (where `base` is the radix). For each index \(k = 0, 1, \dots, length-1\) in the sequence, the output value is computed as \((perm[ (k \bmod base) ] + U) / base\), where `perm` is a randomly shuffled permutation of the digits, and \(U\) is a uniformly distributed random number in `[0, 1)` (to avoid exact boundary values, use `U` sampled from a uniform distribution). The sequence is generated by iterating through indices in order, and for each index, applying the permutation to the digit `(k mod base)`, adding the random fractional part, and dividing by `base`. The function must handle any positive `base` and `length` (including `length` that is not a multiple of `base`; cycle through the permutation naturally). Use a fixed random seed for reproducibility so that the same inputs always produce the same output. The function should return a `std::vector<double>` of length `length` containing these values. For simplicity, use `std::mt19937` for the random permutation and `std::uniform_real_distribution<double>` for the fractional part. This task captures the essence of the digit-wise permutation and randomization from the provided code, simplified to one dimension and one digit.
The core algorithm is to generate a permutation of the digits `0` to `base-1` using a seeded random number generator (`std::mt19937`). For each index `k` in the output sequence, we map the digit `(k % base)` through the permutation to get `permuted_digit`. Then we add a uniformly distributed random number `u` in `[0, 1)`, take the sum, and divide by `base` to obtain a value in `[0, 1)`. This value mimics the digit-wise randomization with a random shift as in the original code, but with only one digit, so there is no need for complex digit tracking or changing-digit logic. The time complexity is \(O(\text{length} + \text{base})\) because we generate the permutation once in \(O(\text{base})\) and then iterate through all `length` indices. The space complexity is \(O(\text{length} + \text{base})\) due to storing the output vector and the permutation. Edge cases include `base = 1` (the permutation is just `{0}`), `length = 0` (return empty vector), and any positive integer for both parameters. The use of a fixed seed ensures reproducibility, which is important for testing. The random fractional part is added to avoid values exactly on the boundary `1/base`, `2/base`, etc., which would cause clustering or invalid values; this ensures the numbers are strictly in `[0, 1)`.
#include <vector>
#include <random>
#include <algorithm>
#include <cstdint>

// Generate a one-dimensional Owen-scrambled digital sequence with one digit and a fixed seed.
// Returns 'length' double values in [0, 1).
std::vector<double> generateRandomizedSequence(int base, int length) {
    if (base <= 0 || length <= 0) {
        return {};
    }

    // Fixed seed for reproducibility.
    std::mt19937 rng(12345); // deterministic seed

    // Create a random permutation of digits [0, base-1].
    std::vector<int> perm(base);
    for (int i = 0; i < base; ++i) {
        perm[i] = i;
    }
    std::shuffle(perm.begin(), perm.end(), rng);

    // Uniform distribution for the fractional part.
    std::uniform_real_distribution<double> dist(0.0, 1.0);

    std::vector<double> result(length);
    for (int k = 0; k < length; ++k) {
        int digit = k % base;             // digit for this index
        int permuted = perm[digit];       // apply permutation
        double u = dist(rng);             // random fraction in [0,1)
        result[k] = (static_cast<double>(permuted) + u) / static_cast<double>(base);
    }

    return result;
}
#include <cassert>
#include <cmath>
#include <vector>
#include <iostream>

int main() {
    // Test basic length and base.
    auto seq1 = generateRandomizedSequence(2, 8);
    assert(seq1.size() == 8);
    for (double v : seq1) {
        assert(v >= 0.0 && v < 1.0);
    }

    // Test reproducibility with same seed.
    auto seq2 = generateRandomizedSequence(3, 5);
    auto seq3 = generateRandomizedSequence(3, 5);
    assert(seq2.size() == 5);
    for (size_t i = 0; i < seq2.size(); ++i) {
        assert(std::abs(seq2[i] - seq3[i]) < 1e-12);
    }

    // Test base=1: only digit 0, so all values should be u/1 = u in [0,1).
    auto seq4 = generateRandomizedSequence(1, 4);
    assert(seq4.size() == 4);
    for (double v : seq4) {
        assert(v >= 0.0 && v < 1.0);
    }

    // Test length=0 returns empty.
    auto seq5 = generateRandomizedSequence(5, 0);
    assert(seq5.empty());

    // Test base=10, length=15: values must be of form (perm + u)/10 within [0,1).
    auto seq6 = generateRandomizedSequence(10, 15);
    assert(seq6.size() == 15);
    for (double v : seq6) {
        assert(v >= 0.0 && v < 1.0);
    }

    // Test that longer sequences cover multiple cycles correctly: length = 2*base.
    auto seq7 = generateRandomizedSequence(4, 8);
    assert(seq7.size() == 8);
    // Check that first half and second half differ due to different random u, even though perm digits repeat.
    // Just verify all in range.
    for (double v : seq7) {
        assert(v >= 0.0 && v < 1.0);
    }

    std::cout << "All tests passed." << std::endl;
    return 0;
}
