// Write a C++ function `long long pythagoreanTripletProduct(int targetSum)` that finds the unique Pythagorean triplet \( (a, b, c) \) with \( a < b < c \), \( a^2 + b^2 = c^2 \), and \( a + b + c = targetSum \) (where `targetSum` is a positive integer, e.g., 1000). The function should return the product \( a \times b \times c \) as a `long long`. If no such triplet exists, return `-1`. The triplet must consist of positive integers only, and the solution must be efficient enough to handle large `targetSum` values (e.g., up to 1,000,000) without iterating through all possible triples naively.

The naive triple nested loop (as in the snippet) is \(O(n^3)\) and infeasible for large sums. Instead, use the algebraic parameterization of Pythagorean triples: all primitive triples can be generated by \( a = m^2 - n^2 \), \( b = 2mn \), \( c = m^2 + n^2 \) for integers \( m > n > 0 \), with \( m \) and \( n \) coprime and of opposite parity. However, the problem does not require primitive triples; it just needs any positive integer triplet, which can be a multiple of a primitive triple. A simpler and direct approach: loop `a` from 1 to `targetSum/3` (since `a < b < c` and sum = targetSum, the smallest `a` cannot exceed `targetSum/3`). For each `a`, loop `b` from `a+1` to `(targetSum - a)/2` (since `c` must be > `b` and the minimum `c` is `b+1`, so `b < (targetSum - a)/2`). Then compute `c = targetSum - a - b` and check if `c > b` and `a*a + b*b == c*c`. This loop is \(O(targetSum^2/12)\) which is fine for targetSum up to ~5000, but for 1,000,000 it is too slow. A better approach: fix `a` and `b`, but instead, use the known formula: `a = k*(m^2 - n^2)`, `b = k*(2mn)`, `c = k*(m^2 + n^2)`. Then `a+b+c = k*(m^2 - n^2 + 2mn + m^2 + n^2) = k*(2m^2 + 2mn) = 2k*m*(m+n)`. So `targetSum = 2*k*m*(m+n)`. This means `targetSum` must be even. So we can iterate `m` from 2 upward, and `n` from 1 to `m-1`, compute `factor = 2*m*(m+n)`, and if `targetSum % factor == 0`, then `k = targetSum / factor`, and we get a valid triplet (with `a = k*(m^2 - n^2)`, `b = k*(2mn)`, `c = k*(m^2 + n^2)`). This is O(m_max^2) where m_max is roughly sqrt(targetSum) because m*(m+n) <= targetSum/2, so m < sqrt(targetSum). That's about 1000 iterations for targetSum=1,000,000, very fast. Edge case: if targetSum is odd, no solution (since sum of a Pythagorean triplet is always even? Actually not always—triples like 3,4,5 sum to 12 even, but 5,12,13 sum to 30 even. It's known that a+b+c is always even for any Pythagorean triple? Yes, because one of a,b is even, c is odd, so sum is even. So odd targetSum returns -1. Also need to ensure a < b < c: for m>n>0, a=m^2-n^2, b=2mn, c=m^2+n^2. Check: is a < b always? Not necessarily: for m=2,n=1, a=3,b=4,c=5 OK. For m=4,n=3, a=7,b=24,c=25 OK. Could a be > b? For m=3,n=2, a=5,b=12 OK. In general, m^2 - n^2 < 2mn iff m^2 - 2mn - n^2 < 0 iff (m/n)^2 - 2(m/n) -1 <0, which holds when m/n < 1+sqrt(2) ≈ 2.414, so for n close to m, a could be larger than b. For example m=5,n=4: a=25-16=9, b=40, still a<b. Actually m=5,n=3: a=16,b=30 OK. The worst case m=2,n=1 gives a=3,b=4. It seems for all m>n>0, m^2-n^2 < 2mn iff m < (1+sqrt(2))n. For m=5,n=2: a=21,b=20, then a>b, so not ordered. Example m=5,n=2 gives a=21,b=20,c=29, sum=70. That is a valid triple but a>b, so we need to swap a and b to satisfy a<b<c. Since the problem just wants product, order doesn't matter for the check; but the function should return the product of the three numbers, so just compute product = a*b*c regardless of which is larger. However, to match the typical definition, we can enforce ordering by sorting the three values, but product is symmetric. So no need. The algorithm: for m from 2 to sqrt(targetSum/2)+1, for n from 1 to m-1, compute denom = 2*m*(m+n). If targetSum % denom == 0, k = targetSum / denom, compute a = k*(m*m - n*n), b = k*(2*m*n), c = k*(m*m + n*n). Then verify a>0,b>0,c>0 and a+b+c==targetSum (holds by construction) and a*a+b*b==c*c (holds by identity). Return product. If loop ends without finding, return -1. Complexity: O(M^2) where M ≈ sqrt(targetSum/2), so O(targetSum) in worst case? Actually M ~ sqrt(targetSum), so O(targetSum). For targetSum=1,000,000, sqrt ≈ 1000, M^2 ≈ 1e6, that's acceptable. Space O(1). Edge cases: targetSum <= 0 return -1; targetSum odd return -1 (since no triple exists). But careful: there exist triples with odd sum? Let's test: a=3,b=4,c=5 sum=12 even. a=8, b=15, c=17 sum=40 even. In general, one of a,b is even, c is odd (if primitive) so sum even. For non-primitive multiples, multiplying by k keeps parity: if primitive sum even, k*even = even. So sum always even. So odd -> -1. Also need to ensure that found triplet has positive integers: since m>n>0, all components positive. Also ensure we don't get duplicates by different (m,n,k) giving same product, but we just return first found, which is fine. The problem states there is at most one triplet for given sum? Actually there could be multiple? For 1000, there is exactly one (200,375,425). But in general, multiple? For sum=840, there are multiple? Possibly. But the task only asks to find one (any) such triplet; the original snippet only prints the first found (well it prints all, but product same? Actually for 1000 it prints one). We'll just return the first found. The function signature: `long long pythagoreanTripletProduct(int targetSum)`.

#include <cmath>

// Find a Pythagorean triplet (a, b, c) with a+b+c == targetSum.
// Return the product a*b*c, or -1 if no such triplet exists.
long long pythagoreanTripletProduct(int targetSum) {
    if (targetSum <= 0 || targetSum % 2 != 0) {
        return -1;
    }

    // Use the parameterization: a = k*(m^2 - n^2), b = k*(2mn), c = k*(m^2 + n^2)
    // Then a+b+c = k * (2m^2 + 2mn) = 2*k*m*(m+n) = targetSum.
    // So iterate m and n such that 2*m*(m+n) divides targetSum.
    int limit = static_cast<int>(std::sqrt(targetSum / 2.0)) + 2;
    for (int m = 2; m <= limit; ++m) {
        for (int n = 1; n < m; ++n) {
            int factor = 2 * m * (m + n);
            if (factor > targetSum) {
                break;
            }
            if (targetSum % factor == 0) {
                int k = targetSum / factor;
                long long a = static_cast<long long>(k) * (m * m - n * n);
                long long b = static_cast<long long>(k) * (2 * m * n);
                long long c = static_cast<long long>(k) * (m * m + n * n);
                // All are positive because m > n > 0 and k > 0.
                // The sum is targetSum by construction; the square relation holds.
                return a * b * c;
            }
        }
    }
    return -1;
}

#include <cassert>

int main() {
    // Original known case: 200 + 375 + 425 = 1000, product = 31875000
    assert(pythagoreanTripletProduct(1000) == 31875000LL);

    // A known primitive triple: 3+4+5=12, product=60
    assert(pythagoreanTripletProduct(12) == 60LL);

    // Another triple: 5+12+13=30, product=780
    assert(pythagoreanTripletProduct(30) == 780LL);

    // Even sum but no valid triplet (e.g., 2) -> -1
    assert(pythagoreanTripletProduct(2) == -1);

    // Odd sum always invalid
    assert(pythagoreanTripletProduct(999) == -1);

    // Non-positive input
    assert(pythagoreanTripletProduct(0) == -1);
    assert(pythagoreanTripletProduct(-100) == -1);

    // Larger multiple: (6,8,10) sum=24, product=480
    assert(pythagoreanTripletProduct(24) == 480LL);

    // Test with a larger valid sum (e.g., 240: 40+96+104? Actually 40+96+104=240, product 399360)
    // Verify via known triple: 40^2+96^2=1600+9216=10816, 104^2=10816, product=40*96*104=399360
    assert(pythagoreanTripletProduct(240) == 399360LL);

    return 0;
}
