/*
Given a company's organizational hierarchy where each employee (except the big boss) reports to exactly one direct superior, write a C++ function `vector<int> buildEulerTour(int n, const vector<int>& bossOf)` that takes the number of employees `n` and an array `bossOf` of length `n` (where `bossOf[i]` is the 1-based index of the direct boss of employee `i`, or `-1` if `i` is the big boss), and returns the Euler tour sequence of employee indices (1-based) generated by a depth-first pre-order traversal with post-order backtracking. The traversal starts at the big boss, visits each employee in increasing order of their employee index among their direct subordinates, and after finishing a subtree, appends the current node again. The output must be a vector of 1-based employee IDs in the exact order produced by this traversal.
*/
#include <vector>

// Build the Euler tour of a rooted tree represented by bossOf (1-based boss, -1 for root).
// Returns a vector of 1-based employee IDs in DFS pre-order with post-order backtracking.
std::vector<int> buildEulerTour(int n, const std::vector<int>& bossOf) {
    // Build adjacency: subordinates[parent] = list of children (0-based indices)
    std::vector<std::vector<int>> subordinates(n);
    int bigBoss = -1;
    for (int i = 0; i < n; ++i) {
        if (bossOf[i] == -1) {
            bigBoss = i;
        } else {
            subordinates[bossOf[i] - 1].push_back(i);
        }
    }

    std::vector<int> euler_tour;
    // Recursive DFS
    std::function<void(int)> dfs = [&](int curr) {
        euler_tour.push_back(curr + 1); // output 1-based
        for (int child : subordinates[curr]) {
            dfs(child);
            euler_tour.push_back(curr + 1); // post-order revisit
        }
    };

    dfs(bigBoss);
    return euler_tour;
}
#include <cassert>
#include <vector>

// The solution function is declared above (or included separately).
int main() {
    // Example from the snippet: n=7, bosses: [2,3,-1,2,3,4,5]? No, correct: input order: employee i with boss list:
    // For i=0: 2, i=1:3, i=2:-1, i=3:2, i=4:3, i=5:4, i=6:5? Actually let's use the snippet's tree: 
    // 1 children 2,3; 2 children 4,5; 3 children 6,7. So bossOf (0-based) = [-1, 1, 1, 2, 2, 3, 3]? Wait, 1-based: employee 1 (index0) boss -1, employee2 (index1) boss 1, employee3 (index2) boss 1, employee4 (index3) boss 2, employee5 (index4) boss 2, employee6 (index5) boss 3, employee7 (index6) boss 3.
    std::vector<int> bossOf7 = {-1, 1, 1, 2, 2, 3, 3};
    std::vector<int> tour7 = buildEulerTour(7, bossOf7);
    std::vector<int> expected7 = {1, 2, 4, 2, 5, 2, 1, 3, 6, 3, 7, 3, 1};
    assert(tour7 == expected7);

    // Single employee
    std::vector<int> bossOf1 = {-1};
    assert(buildEulerTour(1, bossOf1) == std::vector<int>{1});

    // Two employees: boss 1 -> employee 2
    std::vector<int> bossOf2 = {-1, 1};
    assert(buildEulerTour(2, bossOf2) == std::vector<int>({1, 2, 1}));

    // Three in a chain: 1-2-3
    std::vector<int> bossOf3 = {-1, 1, 2};
    assert(buildEulerTour(3, bossOf3) == std::vector<int>({1, 2, 3, 2, 1}));

    // Test increasing child order: root 1 with children 2 and 3, but input order reversed? Children are added in ascending index order by construction, so test that: 2 then 3.
    std::vector<int> bossOf4 = {-1, 1, 1, 2}; // 1 children: 2,3; 2 child 4
    std::vector<int> tour4 = buildEulerTour(4, bossOf4);
    // DFS: 1, then child 2: 2, then child 4: 4,2, then child 3: 3, then back to 1 => 1,2,4,2,3,1
    assert(tour4 == std::vector<int>({1, 2, 4, 2, 3, 1}));

    // Larger balanced tree: size 6, root 1 children 2,3; 2 child 4; 3 child 5,6
    std::vector<int> bossOf6 = {-1, 1, 1, 2, 3, 3};
    std::vector<int> tour6 = buildEulerTour(6, bossOf6);
    // Expected: 1,2,4,2,1,3,5,3,6,3,1
    assert(tour6 == std::vector<int>({1, 2, 4, 2, 1, 3, 5, 3, 6, 3, 1}));

    // Test const correctness: input not modified
    std::vector<int> bossConst = {-1, 1, 1, 2};
    auto tourConst = buildEulerTour(4, bossConst);
    assert(bossConst == std::vector<int>({-1, 1, 1, 2}));
    assert(tourConst.size() == 7); // 2*3-1 = 5? Actually for n=4, 2*(n-1)+1=7

    // Test n=0? Not allowed, but ensure function handles it gracefully? Not required.
    // Test that order respects child index (subordinates sorted by employee index)
    std::vector<int> bossOf5 = {-1, 1, 1, 1}; // root with children 2,3,4
    assert(buildEulerTour(4, bossOf5) == std::vector<int>({1, 2, 1, 3, 1, 4, 1}));
    return 0;
}
// The algorithm is a standard DFS on a rooted tree. First, build an adjacency list from the `bossOf` array: for each employee `i`, if `bossOf[i] != -1`, add `i` (0-based internally) as a child of `bossOf[i]-1`. Identify the big boss as the index with `bossOf[i] == -1`. Then perform a recursive DFS from the big boss: push the current node to the result vector, then recursively visit all children in ascending index order (since we iterate over the adjacency list in increasing order, and children are appended in the loop in that order), and after each child's subtree, push the current node again. Edge cases: if `n == 1`, the tour is just `[1]`. The tree is guaranteed to be rooted and connected by problem nature. Time complexity is `O(n)` because each edge is traversed twice (down and up) and each node is pushed as many times as its degree plus one (in total `2*(n-1)+1 = 2n-1` pushes). Space complexity is `O(n)` for the recursion stack (in worst-case linear tree) and the adjacency list.
