Write a C++ function `findPairwiseSums` that takes a positive integer `n` and a vector of `n` distinct positive integers, each between 1 and 1000000 (inclusive). The function must return a vector of `n` non-negative integers `B` (each between 0 and 1000000) such that all pairwise sums `A[i] + B[j]` (for all `1 <= i,j <= n`) are distinct modulo the given constraints—specifically, that no two such sums share the same value. More precisely, construct `B` so that for every fixed `i`, the values `{A[i] + B[j]}` are all distinct, and for any two different `i` and `k`, the sets `{A[i] + B[j]}` and `{A[k] + B[j]}` are disjoint (i.e., no sum from one set equals a sum from the other set). If it is possible, return the constructed `B` vector in any order. If impossible (e.g., when `A` contains duplicate elements), return an empty vector. You may assume `n` is at most 100 and each `A[i]` is within the stated range. The function must be `const`-correct and include necessary headers.

// The solution uses a greedy constructive approach based on the observation that if all `A[i]` are distinct, we can always find a valid `B` by scanning candidate offsets in increasing order from 0 upward. For each candidate offset `x`, we check if adding `x` to every element of `A` produces sums that do not collide with any sums already generated by previously fixed `B` values. To do this efficiently, we maintain a boolean array `seen[2000005]` (or similar) that marks values already used as sums. When we choose a new offset `x`, we verify that for every `j`, `A[j] + x` is not already marked in `seen`. If so, we add `x` to `B` and mark all `A[j] + x` as seen. We continue until we have `n` offsets. If during the process we exhaust the candidate range (we limit the search to offsets up to 1000000, which is enough because the maximum possible sum is 2000000 and the array size is 2000005), we conclude it is impossible and return an empty vector. The distinctness of `A` is checked first: if any duplicate exists, it is impossible because duplicates would cause identical sums regardless of `B`. Time complexity is `O(n * M)` where `M` is the search range (up to 1000000) in the worst case, but in practice it terminates early because the density of unused sums is high. Space complexity is `O(2000005)` for the `seen` array plus `O(n)` for the result.

#include <vector>
#include <cstring>

// Given a vector of distinct positive integers A (size n), return a vector B of length n
// such that all pairwise sums A[i] + B[j] are distinct across all i and j.
// If impossible (duplicate in A), return empty vector.
std::vector<int> findPairwiseSums(const std::vector<int>& A) {
    int n = (int)A.size();
    // Check for duplicates
    std::vector<bool> hasSeen(1000001, false);
    for (int val : A) {
        if (hasSeen[val]) return {};
        hasSeen[val] = true;
    }
    
    // seenSums will mark used sums. Maximum possible sum is A_max + B_max <= 1000000+1000000 = 2000000.
    // We'll use an array of size 2000005.
    static bool seenSums[2000005];
    std::memset(seenSums, 0, sizeof(seenSums));
    
    std::vector<int> B;
    B.reserve(n);
    
    // Try offsets from 0 upward
    for (int x = 0; x <= 1000000 && (int)B.size() < n; ++x) {
        bool valid = true;
        // Check if this offset collides with any existing sum
        for (int a : A) {
            if (seenSums[a + x]) {
                valid = false;
                break;
            }
        }
        if (valid) {
            B.push_back(x);
            // Mark all sums produced by this offset
            for (int a : A) {
                seenSums[a + x] = true;
            }
        }
    }
    
    if ((int)B.size() < n) return {};
    return B;
}

#include <cassert>
#include <vector>
#include <set>

// The solution function is declared above. Test it here.
int main() {
    // Basic test: A = {1,2,3} distinct, should produce a valid B of size 3
    {
        std::vector<int> A = {1,2,3};
        std::vector<int> B = findPairwiseSums(A);
        assert(B.size() == 3);
        // Verify all pairwise sums are distinct
        std::set<int> sums;
        for (int a : A) for (int b : B) sums.insert(a + b);
        assert((int)sums.size() == 9); // 3*3 = 9 distinct sums
    }
    // Duplicate input -> empty vector
    {
        std::vector<int> A = {5,5};
        assert(findPairwiseSums(A).empty());
    }
    // Single element -> B can be {0}
    {
        std::vector<int> A = {42};
        std::vector<int> B = findPairwiseSums(A);
        assert(B.size() == 1);
        assert(B[0] == 0);
    }
    // Larger distinct set
    {
        std::vector<int> A = {10,20,30,40,50};
        std::vector<int> B = findPairwiseSums(A);
        assert(B.size() == 5);
        std::set<int> sums;
        for (int a : A) for (int b : B) sums.insert(a + b);
        assert((int)sums.size() == 25);
    }
    // Edge: A contains 1 and 1000000, distinct
    {
        std::vector<int> A = {1, 1000000};
        std::vector<int> B = findPairwiseSums(A);
        assert(B.size() == 2);
        std::set<int> sums;
        for (int a : A) for (int b : B) sums.insert(a + b);
        assert((int)sums.size() == 4);
    }
    // Large n = 100 with distinct values
    {
        std::vector<int> A;
        for (int i = 1; i <= 100; ++i) A.push_back(i);
        std::vector<int> B = findPairwiseSums(A);
        assert(B.size() == 100);
        std::set<int> sums;
        for (int a : A) for (int b : B) sums.insert(a + b);
        assert((int)sums.size() == 10000);
    }
    return 0;
}
