Write a C++ function named `blumBlumShubPRNG` that takes three `unsigned long long` integers as parameters: `p`, `q`, and `seed`, where `p` and `q` are primes and `seed` is a quadratic residue modulo the product `n = p * q`. The function must simulate the first 32 bits of the Blum Blum Shub (BBS) pseudo-random generator, specifically the output of `GenerateByte()` called four times in sequence. For each of the four bytes, produce 8 bits by repeatedly squaring the current state modulo `n` (starting from `state = (seed * seed) % n` for the first byte, then squaring the previous final state for subsequent bytes), and take the least significant bit of the intermediate state before each squaring operation. Assemble these bits into a byte, with the first generated bit as the most significant bit. Return a `std::array<unsigned char, 4>` containing the four generated bytes in order. Assume `p` and `q` are distinct odd primes, `n > 0`, and `seed > 0`; the result must be computed using 64-bit arithmetic, and the function should handle any overflow via modulo reduction after each multiplication. The solution must be self-contained, include necessary headers, and apply `const` correctness where appropriate.
#include <cassert>
#include <array>

// The function declaration is assumed from the solution.
std::array<unsigned char, 4> blumBlumShubPRNG(unsigned long long p, unsigned long long q, unsigned long long seed);

int main() {
    // Test with small primes and seed.
    // n = 11 * 19 = 209, seed = 5 (quadratic residue? 5^2=25 mod 209=25)
    auto result1 = blumBlumShubPRNG(11, 19, 5);
    // Compute manually: state starts as 25, bits (LSB first): 25&1=1, then 25^2=625 mod209=625-3*209=625-627=-2 => 207, 207&1=1, 207^2=42849 mod209=42849-204*209=42849-42636=213? Actually 209*205=42845, so 42849-42845=4, 4&1=0, 4^2=16&1=0, 16^2=256 mod209=47, 47&1=1, 47^2=2209 mod209=2209-209*10=2209-2090=119, 119&1=1, 119^2=14161 mod209=14161-209*67=14161-14003=158, 158&1=0, 158^2=24964 mod209=24964-209*119=24964-24871=93, 93&1=1. So bits (from first to last) 1,1,0,0,1,1,0,1 => byte = 0b11001101 = 205. Then state=93 for next byte. Continue... We only assert that the result is deterministic; for a small test we can compare to a known output. Since exact manual computation is tedious, we use a simpler test with n=3*5=15, seed=1. Then state=1, bits all 1? Because 1^2=1 always. So each byte is 0xFF. So result should be all 255.
    auto result2 = blumBlumShubPRNG(3, 5, 1);
    for (int i = 0; i < 4; ++i) {
        assert(result2[i] == static_cast<unsigned char>(0xFF));
    }

    // Test with n=7*11=77, seed=4 (4^2=16 mod77=16). Then state sequence: 16 -> 16^2=256 mod77=256-231=25 -> 25^2=625 mod77=625-616=9 -> 9^2=81 mod77=4 -> 4^2=16 cycles. Bits: 16 LSB 0, then 25 LSB1, then 9 LSB1, then 4 LSB0, then repeat. So for first byte bits: 0,1,1,0,0,1,1,0 => 0b01100110=102. Next state after last bit is 16? Actually let's compute: start state=16, bit0=0, then square to 25, bit1=1, square to 9, bit2=1, square to 4, bit3=0, square to 16, bit4=0, square to 25, bit5=1, square to 9, bit6=1, square to 4, bit7=0, then state after byte=4 (since after squaring at bit7 we got 4). Next byte: bits from 4: 0, then 16 (0), then 25(1), then 9(1), then 4(0), then 16(0), then 25(1), then 9(1) => 0b00110011=51. Let's compute expected result: {102, 51? then next: after bit7 square from 9 to 4, next state=4, so byte2 same as byte2? Actually after byte1 state=4, so byte2 bits: 0,16(0),25(1),9(1),4(0),16(0),25(1),9(1) => 0b00110011=51. After byte2 state=4 again? Wait after byte2 last bit we square from 9 to 4, so yes state=4. So byte2=51, byte3=51. So result = {102, 51, 51, 51}.
    auto result3 = blumBlumShubPRNG(7, 11, 4);
    assert(result3[0] == 102);
    assert(result3[1] == 51);
    assert(result3[2] == 51);
    assert(result3[3] == 51);

    // Test p=11, q=13, seed=3. n=143. seed^2=9. State: 9 ->81-> 81^2=6561 mod143 = 6561-45*143=6561-6435=126 ->126^2=15876 mod143=15876-111*143=15876-15873=3 ->3^2=9 cycles. Bits: 9(1),81(1),126(0),3(1),9(1),81(1),126(0),3(1) => 0b11011011=219? Actually 1,1,0,1,1,1,0,1 = 0b11011101=221. Then state after byte=3 (since from 3^2=9, but we have it as next? let's do carefully: start 9 bit1, square to 81 bit1, square to 126 bit0, square to 3 bit1, square to 9 bit1, square to 81 bit1, square to 126 bit0, square to 3 bit1, so bits: 1,1,0,1,1,1,0,1 => 0b11011101=221. State=3 after last square. Next byte: 3(1),9(1),81(1),126(0),3(1),9(1),81(1),126(0) => 0b11101110=238. Then state after byte: from 126^2=3? Actually after bit7 we square from 126 to 3, so state=3 again, so next byte same as byte1? Wait sequence: after byte1 state=3, byte2 bits: 3(1),9(1),81(1),126(0),3(1),9(1),81(1),126(0) => 0b11101110=238, state after byte2 = 3 (because after bit7 we square from 126 to 3? Actually bit7 is from state=126? Let's enumerate: bit0 from 3:1, then square to 9; bit1 from 9:1, square to 81; bit2 from81:1, square to126; bit3 from126:0, square to3; bit4 from3:1, square to9; bit5 from9:1, square to81; bit6 from81:1, square to126; bit7 from126:0, square to3. So bits: 1,1,1,0,1,1,1,0 => 0b11101110=238, state after byte2=3. So byte3 same as byte2? Actually after byte2 state=3, so byte3 bits same as byte2 -> 238, same for byte4. So result = {221, 238, 238, 238}.
    auto result4 = blumBlumShubPRNG(11, 13, 3);
    assert(result4[0] == 221);
    assert(result4[1] == 238);
    assert(result4[2] == 238);
    assert(result4[3] == 238);

    // Test with seed=0? Not allowed by spec (seed>0), but for completeness let's skip.
    // Test with p=3, q=7 (n=21), seed=2 (2^2=4). State sequence: 4->16->256 mod21=256-252=4, cycle. Bits: 4(0),16(0),4(0),16(0),... All 0, so all bytes 0.
    auto result5 = blumBlumShubPRNG(3, 7, 2);
    for (int i = 0; i < 4; ++i) {
        assert(result5[i] == 0);
    }

    return 0;
}
#include <array>
#include <cstdint>

// Simulate the first 32 bits (4 bytes) of the Blum Blum Shub PRNG.
// p and q are distinct odd primes, n = p * q, seed is a quadratic residue modulo n.
// Returns four bytes; each byte's most significant bit is the first generated bit.
std::array<unsigned char, 4> blumBlumShubPRNG(unsigned long long p, unsigned long long q, unsigned long long seed) {
    const unsigned long long n = p * q;
    unsigned long long current = (seed * seed) % n;

    std::array<unsigned char, 4> result;

    for (int byteIndex = 0; byteIndex < 4; ++byteIndex) {
        unsigned char byte = 0;
        for (int bitIndex = 7; bitIndex >= 0; --bitIndex) {
            // Extract the least significant bit and place it in the byte.
            unsigned char bit = static_cast<unsigned char>(current & 1ULL);
            byte = static_cast<unsigned char>((byte << 1) | bit);

            // Square the state modulo n, using __int128 to avoid overflow.
            unsigned __int128 product = static_cast<unsigned __int128>(current) * current;
            current = static_cast<unsigned long long>(product % n);
        }
        result[byteIndex] = byte;
    }

    return result;
}
// The task mirrors the core of the BBS generator from the snippet, but simplified to a fixed single-shot generation of 32 bits using only `unsigned long long` arithmetic (no big integer support). The algorithm processes bytes sequentially. For each byte, we maintain an internal state `current` initialized as `(seed * seed) % n` for the first byte, and after each byte we set `current = (current * current) % n` (since after generating a byte, the snippet squaring happens at the start of the next byte's bit generation; however, the sequence in the snippet for the very first byte uses `current = modn.Square(modn.Square(seed))` due to initialization, but the task explicitly defines the state initialization differently: we start with `current = (seed * seed) % n` and then generate bits by taking the least significant bit of `current`, followed by updating `current = (current * current) % n` for the next bit). To match the intended behavior, we generate 8 bits per byte: for each bit, extract `(current & 1)`, push it into the byte (starting from MSB), then update `current = (current * current) % n`. After all 8 bits, move to the next byte but note that the state is already the squared value after the last bit of the previous byte, so for the next byte we simply continue using that state. The generation is purely deterministic. Edge cases: when `n` is small, `current` may become 0 or 1, but the algorithm still works (bits then become 0 or alternating 1/0 respectively). The multiplication `current * current` may overflow `unsigned long long` (which is 64-bit); however, since we take the result modulo `n` immediately, and `n` is at most the product of two 32-bit primes (which can be up to about 2^64), the product might overflow before modulo. To avoid that, we can use `unsigned __int128` for the multiplication (available on GCC/Clang and MSVC) to compute the product exactly then reduce modulo `n`. The time complexity is O(32) operations (since we generate exactly 32 bits, each requiring a constant-time square and modulo), and O(1) auxiliary space. The function is `const`-correct and returns a `std::array<unsigned char, 4>`.
