/*
Create a C++ function named `markSelfNumbers` that takes an integer `limit` and returns a `std::vector<bool>` of size `limit + 1`, where each element at index `i` is `true` if `i` is a "self number" (a number that is not the result of a generator function `d(n) = n + sum of digits of n`), and `false` otherwise. The function must correctly mark all non-self numbers up to and including `limit`. Assume `limit` is at least 1 and at most 10000. The returned vector must have index 0 set to `false` (since 0 is not considered a self number in this context), and indices 1 through `limit` correctly computed. The function should not print anything and must be `const`-correct where applicable.
*/
#include <vector>

// Returns a vector where index i is true if i is a self number (i.e., not generated).
std::vector<bool> markSelfNumbers(int limit) {
    // Initialize all numbers as self (true). Index 0 is unused and set false.
    std::vector<bool> isSelf(limit + 1, true);
    if (limit >= 0) {
        isSelf[0] = false; // 0 is not considered a self number.
    }

    // For each number n, generate d(n) = n + sum of digits of n.
    for (int n = 1; n <= limit; ++n) {
        int generated = n;
        int temp = n;
        while (temp > 0) {
            generated += temp % 10;
            temp /= 10;
        }
        // Mark the generated number as not self, if within range.
        if (generated <= limit && generated > 0) {
            isSelf[generated] = false;
        }
    }
    return isSelf;
}
#include <cassert>
#include <vector>

// (The solution function is assumed to be included above.)

int main() {
    // limit = 1: only 1 is self (since d(1)=2 > 1)
    std::vector<bool> r1 = markSelfNumbers(1);
    assert(r1.size() == 2);
    assert(r1[0] == false);
    assert(r1[1] == true);

    // limit = 20: self numbers are 1,3,5,7,9,20 (known sequence)
    std::vector<bool> r2 = markSelfNumbers(20);
    for (int i = 1; i <= 20; ++i) {
        bool expected = (i == 1 || i == 3 || i == 5 || i == 7 || i == 9 || i == 20);
        assert(r2[i] == expected);
    }

    // limit = 100: first few self numbers are 1,3,5,7,9,20,31,42,53,64,75,86,97
    std::vector<bool> r3 = markSelfNumbers(100);
    assert(r3[1] == true);
    assert(r3[3] == true);
    assert(r3[20] == true);
    assert(r3[31] == true);
    assert(r3[42] == true);
    assert(r3[53] == true);
    assert(r3[64] == true);
    assert(r3[75] == true);
    assert(r3[86] == true);
    assert(r3[97] == true);
    assert(r3[100] == false); // 100 = 86 + (8+6) ? check: 86+14=100? Actually 86+14=100, yes.
    assert(r3[99] == false);  // 99 is generated by 79? 79+16=95? Let's just check: 99 is not self because 99 = 82+10? 82+10=92, no. 97+16=113 too big. Actually 99 is self? Let's compute known: 99 is not self? Known self numbers up to 100 include 97, then next is 108. So 98,99 are not self? Wait, 98=?? Actually 98 = 79+16=95 no. Let's not assert on uncertain numbers. Instead check known self numbers from 1 to 100 are: 1,3,5,7,9,20,31,42,53,64,75,86,97. So assert those are true and all others false. We already did some. Add loop:
    for (int i = 1; i <= 100; ++i) {
        bool known_self = (i==1||i==3||i==5||i==7||i==9||i==20||i==31||i==42||i==53||i==64||i==75||i==86||i==97);
        assert(r3[i] == known_self);
    }

    // limit = 10000 (max): just check size and that 1 is true, 0 false
    std::vector<bool> r4 = markSelfNumbers(10000);
    assert(r4.size() == 10001);
    assert(r4[0] == false);
    assert(r4[1] == true);
}
// The solution mimics the process of "generating" numbers using the digit-sum function. For each number `n` from 1 to `limit`, compute `next = n + sum of digits(n)`. If `next <= limit`, mark `next` as not self (set to `false`). This works because every number that is not self is generated by exactly one such `n`. To avoid missing numbers, we must iterate `n` from 1 to `limit` and mark all generated numbers. The key edge case is that `n` itself can be less than `limit` and generate a number greater than `limit` (ignored), and numbers near the top of the range are rarely generated because their generators are smaller. Also, 0 is always `false` because there is no positive integer `n` that generates 0 (since `n >= 1`, `n + digit sum >= 1`). The time complexity is O(limit * digit_count) which is effectively O(limit log10(limit)), but since limit ≤ 10000, it's effectively O(limit). Space complexity is O(limit) for the vector.
