Write a C++ function that simulates the recursive subdivision of a tetrahedron for a given recursion depth `m`, but instead of rendering OpenGL graphics, it should compute and return the total number of triangles that would be drawn at the deepest level of recursion (i.e., when `m` reaches 0). The input is a non-negative integer `m` representing the subdivision depth. For `m = 0`, the function should return 4 (a single tetrahedron has 4 triangular faces). For each level of subdivision, every tetrahedron is replaced by 4 new tetrahedrons, so the number of triangles grows accordingly. The function must handle edge cases such as very large `m` (up to, say, 30) without overflow by returning a 64-bit integer. Do not use any graphics library—pure arithmetic and recursion (or direct formula) are sufficient.

// The key observation is that each recursive call on a tetrahedron with depth `m > 0` creates 4 sub-tetrahedrons, each with depth `m-1`. Therefore, the total number of triangles at the base case (m=0) is simply `4^(m+1)`? Wait: Let's check. For m=0, we have 1 tetrahedron, each with 4 triangles → 4 triangles total. For m=1, we subdivide into 4 tetrahedrons, each with 4 triangles → 16 triangles. For m=2 → 64 triangles. In general, the total number of triangles is `4 * 4^m = 4^(m+1)`. However, careful: The recursion tree: each call at depth `k` creates 4 calls at depth `k-1`. So the number of leaves (depth 0) is `4^m`. Each leaf draws 4 triangles. So total = `4 * 4^m = 4^(m+1)`. That matches: m=0 → 4, m=1 → 16, m=2 → 64. 
//
// But wait, the original code subdivides and draws tetrahedrons only at the base case (when m==0). Each base-case tetrahedron draws 4 triangles. So the formula is correct. However, there is a nuance: In the subdivision, each tetrahedron is divided into 4 smaller tetrahedrons, but some faces might be shared? Actually, in geometric subdivision, internal faces are not drawn because they are shared by two tetrahedrons; but the original code simply draws all faces of each sub-tetrahedron, so it overcounts shared faces. Since the task is pure arithmetic, we just follow the recursion count, not geometric visibility. So the answer is `4^(m+1)`.
//
// Edge cases: m=0 gives 4; m very large could overflow a 32-bit int, so use `long long` or `uint64_t`. For m=30, 4^31 is about 4.6e18, which fits in 64-bit. For m=31 it overflows 64-bit? 4^32 = 2^64, which overflows signed 64-bit (max ~9.22e18). So we can cap at m=30 or use unsigned. The task says up to 30, so fine. The recursive approach is O(m) depth but number of calls is 4^m, which is huge. So we should compute directly using exponentiation, not recursion. The analysis will mention that a direct formula is O(log m) or O(1) using bit shift since 4^(m+1) = 2^(2*(m+1)). 
//
// Implementation: `std::uint64_t countTriangles(int m)` returns `1ULL << (2*(m+1))` when m >= 0. But for m=30, 2*(30+1)=62, so 2^62 fits in 64-bit. For m=31, 2^64 overflow. So we check that m <= 30. If m < 0, return 0? The task says non-negative, so no need. 
//
// Time complexity: O(1) or O(log m) if using exponentiation by squaring, but bit shift is O(1). Space O(1).

#include <cstdint>
#include <stdexcept>

// Count the total number of triangles generated by subdividing a tetrahedron
// recursively for `depth` levels. Each subdivision replaces one tetrahedron
// with four smaller tetrahedrons; the base case (depth 0) draws 4 triangular faces.
std::uint64_t count_triangles(int depth) {
    if (depth < 0) {
        throw std::invalid_argument("depth must be non-negative");
    }
    // Each level multiplies triangle count by 4. For depth d, total = 4^(d+1).
    // Since 4 = 2^2, we can use a bit shift on a 64-bit integer.
    // Maximum depth that fits in uint64_t is 30 (since 2^(2*(30+1)) = 2^62).
    if (depth > 30) {
        throw std::overflow_error("depth too large for 64-bit result");
    }
    return std::uint64_t{1} << (2 * (depth + 1));
}

#include <cstdint>
#include <cassert>
#include <stdexcept>

// (Include the solution function here)

int main() {
    // Base case: a single tetrahedron has 4 triangles.
    assert(count_triangles(0) == 4);
    // One subdivision: 4 tetrahedrons each with 4 triangles = 16.
    assert(count_triangles(1) == 16);
    // Two subdivisions: 4^3 = 64.
    assert(count_triangles(2) == 64);
    // Verify a moderate depth: depth 3 -> 4^4 = 256.
    assert(count_triangles(3) == 256);
    // Larger depth: depth 10 -> 4^11 = 4,194,304.
    assert(count_triangles(10) == 4194304ULL);
    // Edge: depth 30 -> 2^62 = 4,611,686,018,427,387,904.
    assert(count_triangles(30) == 4611686018427387904ULL);
    // Negative depth should throw.
    bool threw = false;
    try {
        count_triangles(-1);
    } catch (const std::invalid_argument&) {
        threw = true;
    }
    assert(threw);
    // Depth 31 causes overflow.
    threw = false;
    try {
        count_triangles(31);
    } catch (const std::overflow_error&) {
        threw = true;
    }
    assert(threw);
}
