// Write a standalone C++ function named `buildMeanPatch` that takes a square grayscale image represented as a 2D vector of floats (row-major) and an integer `pose_count` (greater than 0), and returns a new 2D vector of the same dimensions containing the average of `pose_count` perturbed versions of the input image. Each perturbed version is generated by: (1) applying a random brightness multiplier in the range `[0.85, 1.15]` to every pixel, (2) adding a uniformly random pixel-wise noise value in the range `[-0.05, 0.05]` to each pixel independently, and (3) clipping all resulting values to the valid range `[0.0, 1.0]`. The function must use a deterministic random number generator seeded with a fixed constant (e.g., `12345`) so that repeated calls produce identical results. The returned image should contain the element-wise average of the perturbed images (not clipped after averaging). The task must be self-contained, not depend on any image-processing library, and include proper handling of edge cases such as an empty input or non-square input (return an empty vector if input is empty or not square). Use `std::vector` and standard library facilities only.

// The solution follows a straightforward Monte Carlo averaging approach. For each of the `pose_count` iterations, we create a copy of the input image, then for every pixel we: (1) compute a brightness multiplier using a uniform random real distribution between 0.85 and 1.15 (seeded from a global fixed seed), (2) add a uniform random noise value between -0.05 and 0.05, (3) clamp to [0.0, 1.0]. After generating each perturbed image, we add it to an accumulator (a 2D vector of doubles to avoid precision loss). Finally, we divide by `pose_count` to obtain the average. Edge cases: if the input is empty or not square, we return an empty vector. The time complexity is O(pose_count * N), where N is the number of pixels (width*height). The space complexity is O(N) for the accumulator, plus O(N) for each temporary perturbed image (which can be avoided by reusing a single temporary buffer). We misuse a fixed seed to ensure deterministic output, and we use `std::mt19937` and `std::uniform_real_distribution<float>` for randomness.

#include <vector>
#include <random>
#include <algorithm>
#include <cstddef>

/**
 * Builds the average of perturbed versions of a square grayscale image.
 * 
 * @param input A square row-major grayscale image with values in [0.0, 1.0].
 * @param pose_count Number of perturbed samples to average. Must be > 0.
 * @return Averaged image (not clipped) of same size, or empty if input is invalid.
 */
std::vector<std::vector<float>> buildMeanPatch(
    const std::vector<std::vector<float>>& input,
    int pose_count
) {
    // Validate input
    if (input.empty() || pose_count <= 0) {
        return {};
    }
    const std::size_t rows = input.size();
    const std::size_t cols = input[0].size();
    if (rows != cols) {
        return {};
    }
    // Check all rows have same width
    for (const auto& row : input) {
        if (row.size() != cols) {
            return {};
        }
    }

    // Fixed deterministic seed
    std::mt19937 gen(12345);
    std::uniform_real_distribution<float> brightness_dist(0.85f, 1.15f);
    std::uniform_real_distribution<float> noise_dist(-0.05f, 0.05f);

    // Accumulator as double for precision
    std::vector<std::vector<double>> accumulator(rows, std::vector<double>(cols, 0.0));
    std::vector<std::vector<float>> perturbed(rows, std::vector<float>(cols, 0.0f));

    for (int sample = 0; sample < pose_count; ++sample) {
        // Generate a perturbed version
        for (std::size_t r = 0; r < rows; ++r) {
            for (std::size_t c = 0; c < cols; ++c) {
                float brightness = brightness_dist(gen);
                float noise = noise_dist(gen);
                float value = input[r][c] * brightness + noise;
                // Clip to [0.0, 1.0]
                value = std::max(0.0f, std::min(1.0f, value));
                perturbed[r][c] = value;
                // Accumulate (convert to double)
                accumulator[r][c] += static_cast<double>(value);
            }
        }
    }

    // Compute average
    std::vector<std::vector<float>> result(rows, std::vector<float>(cols, 0.0f));
    double inv_count = 1.0 / pose_count;
    for (std::size_t r = 0; r < rows; ++r) {
        for (std::size_t c = 0; c < cols; ++c) {
            result[r][c] = static_cast<float>(accumulator[r][c] * inv_count);
        }
    }
    return result;
}

#include <cassert>
#include <cmath>
#include <iostream>
#include <vector>

// Function prototype (same as above, but we include the actual definition earlier)
// For this test, we reference the function.

int main() {
    // Test 1: Simple 1x1 image with a single pixel value.
    std::vector<std::vector<float>> img1 = {{0.5f}};
    auto out1 = buildMeanPatch(img1, 100);
    assert(out1.size() == 1);
    assert(out1[0].size() == 1);
    // With many samples, average should be near 0.5 + average noise (0) * brightness ~ 0.5
    // but deterministic, so we just check it is in a plausible range.
    assert(out1[0][0] >= 0.4f && out1[0][0] <= 0.6f);

    // Test 2: Determinism - calling twice gives identical result.
    std::vector<std::vector<float>> img2 = {{0.2f, 0.8f}, {0.3f, 0.7f}};
    auto out2a = buildMeanPatch(img2, 50);
    auto out2b = buildMeanPatch(img2, 50);
    assert(out2a == out2b);

    // Test 3: Empty input returns empty.
    std::vector<std::vector<float>> empty;
    assert(buildMeanPatch(empty, 5).empty());

    // Test 4: Non-square input returns empty.
    std::vector<std::vector<float>> nonSquare = {{0.1f, 0.2f}, {0.3f}};
    assert(buildMeanPatch(nonSquare, 5).empty());

    // Test 5: pose_count = 0 returns empty.
    assert(buildMeanPatch(img1, 0).empty());

    // Test 6: With pose_count = 1, output should be a valid clipped perturbed version.
    auto out3 = buildMeanPatch(img2, 1);
    // Each output pixel must be between 0 and 1 (perturbed and clipped).
    for (const auto& row : out3) {
        for (float v : row) {
            assert(v >= 0.0f && v <= 1.0f);
        }
    }

    // Test 7: Average of a large sample of a constant image stays near the original.
    std::vector<std::vector<float>> constImg = {{0.5f, 0.5f}, {0.5f, 0.5f}};
    auto out4 = buildMeanPatch(constImg, 5000);
    for (const auto& row : out4) {
        for (float v : row) {
            // Brightness multiplier average is 1.0 and noise average is 0, so mean should be near 0.5
            assert(std::fabs(v - 0.5f) < 0.05f);
        }
    }

    // Test 8: Shape is preserved.
    std::vector<std::vector<float>> img5(4, std::vector<float>(4, 0.0f));
    auto out5 = buildMeanPatch(img5, 10);
    assert(out5.size() == 4);
    assert(out5[0].size() == 4);

    std::cout << "All tests passed!" << std::endl;
    return 0;
}
