/*
Write a C++ function `generatePattern` that takes three integers `n`, `a`, and `b` (where `1 <= n <= 1000`, `1 <= a, b <= 26`) and returns a string of length `n` formed by repeating a block of length `b` that starts with the lowercase letter corresponding to `a` (where `1` maps to `'a'`, `2` to `'b'`, ... `26` to `'z'`). The block itself is generated by taking each position `i` in the block (0-indexed) and writing the letter at index `(a + i - 1) % 26` (so the block cycles through letters starting from `a`). Then the whole block is repeated to fill exactly `n` characters. For example, if `n=10`, `a=2`, `b=3`, the block is `b c d`, and the output is "bcdbcdbcdb". Note that `b` may be larger than 26, in which case the block letters wrap around the alphabet repeatedly . The function must use `const` where appropriate and be self-contained.
*/

#include <string>

// Generate a string of length n by repeating a cyclic pattern of letters.
// The pattern is a block of length b, where the letter at position i (0-indexed)
// is determined by starting at letter 'a' + (a-1) and cycling through the alphabet.
std::string generatePattern(int n, int a, int b) {
    std::string result;
    result.reserve(n);

    // Build the block of length b first.
    std::string block;
    block.reserve(b);
    for (int i = 0; i < b; ++i) {
        char c = static_cast<char>('a' + ((a - 1 + i) % 26));
        block.push_back(c);
    }

    // Repeat the block to fill length n.
    for (int i = 0; i < n; ++i) {
        result.push_back(block[i % b]);
    }

    return result;
}

#include <cassert>
#include <string>

// Declare the function (since it's separate from test).
std::string generatePattern(int n, int a, int b);

int main() {
    // Basic example from statement.
    assert(generatePattern(10, 2, 3) == "bcdbcdbcdb");

    // n smaller than b: just the first n characters of the block.
    assert(generatePattern(2, 5, 4) == "ef");

    // b larger than 26: wraps alphabet.
    assert(generatePattern(5, 25, 28) == "yzabcd");

    // a=1, b=26: full alphabet once, then repeat.
    assert(generatePattern(30, 1, 26) == "abcdefghijklmnopqrstuvwxyzabcd");

    // b=1, so entire output is the same letter.
    assert(generatePattern(7, 3, 1) == "ccccccc");

    // a=26 (z) and b=3: starts with z.
    assert(generatePattern(6, 26, 3) == "zabzab");

    // n=1 always works.
    assert(generatePattern(1, 10, 5) == "j");

    // n=0? Not in spec, but function should handle gracefully (return empty).
    assert(generatePattern(0, 1, 1) == "");

    // Large b and n, check length and first character.
    std::string big = generatePattern(1000, 7, 100);
    assert(big.size() == 1000);
    assert(big[0] == 'g');  // 'a' + (7-1) = 'g'

    return 0;
}

// The key is to first construct the block of length `b`. For each index `i` from 0 to `b-1`, the letter is `'a' + ((a - 1 + i) % 26)`. This handles arbitrary `a` and `b` correctly; if `a` is 26 (z), then `a-1=25`, and the modulo wraps correctly. After building the block string (size `b`), we need to repeat it to produce a string of length `n`. Since `n` might not be a multiple of `b`, we can either append whole copies and then add the remaining prefix, or loop `n` times appending `block[i % b]`. The latter is simpler and avoids special cases. Edge cases: `b=0`? The problem states `b>=1`, so safe. If `n` is smaller than `b`, we just take the first `n` characters of the block. Time complexity is O(n) because we iterate exactly `n` times; space O(n) for the output string. No extra data structures needed beyond the constructed block of size `b`.
