// Write a C++ function that takes two strings, `s` and `t`, where `t` is generated by shuffling the characters of `s` and adding one extra character at a random position. The function should return the extra character that was added. The strings consist only of lowercase English letters, and the length of `t` is exactly one greater than the length of `s`. For example, if `s = "abcd"` and `t = "abcde"`, the function should return `'e'`. If the extra character is a duplicate of an existing character, such as `s = "a"` and `t = "aa"`, the function should still return `'a'`. The function must handle empty input for `s` (in which case `t` is a single character). Assume the inputs are always valid per the specification.

#include <cassert>

int main() {
    // Basic cases
    assert(findExtraCharacter("abcd", "abcde") == 'e');
    assert(findExtraCharacter("", "z") == 'z');
    assert(findExtraCharacter("abc", "abca") == 'a');

    // Duplicate extra character
    assert(findExtraCharacter("a", "aa") == 'a');
    assert(findExtraCharacter("xyz", "xyzz") == 'z');

    // Longer strings with multiple duplicates
    assert(findExtraCharacter("hello", "helxlo") == 'x');
    assert(findExtraCharacter("software", "softwqare") == 'q');

    // All same characters
    assert(findExtraCharacter("aaaa", "aaaaa") == 'a');

    // Already in order but shuffled
    assert(findExtraCharacter("abc", "cbaa") == 'a');
    assert(findExtraCharacter("12345", "123456") == '6'); // Note: function works for any char, not just letters

    // Shuffled t
    assert(findExtraCharacter("abc", "bacd") == 'd');

    return 0;
}

#include <string>

// Returns the extra character added to string t relative to string s.
char findExtraCharacter(const std::string& s, const std::string& t) {
    char result = 0;
    for (char c : s) {
        result ^= c;
    }
    for (char c : t) {
        result ^= c;
    }
    return result;
}

// The simplest approach is to use a hash map (e.g., `std::unordered_map<char, int>`) to count the frequency of each character in string `s`. Then iterate through string `t`, and for each character, decrement its count in the map if it exists. The character whose count becomes negative (or that doesn't exist in the map) is the extra character. However, a more efficient and elegant solution uses the XOR bitwise operator: since `a ^ a = 0` and XOR is commutative and associative, XORing all characters from both strings together will cancel out all pairs, leaving only the extra character. This avoids extra space. Edge cases: when `s` is empty (then `t` is a single character, and XOR of that single character returns it), and when the extra character duplicates an existing one (still works because the odd occurrence remains). Time complexity is O(n) where n is the length of `t` (or `s`+1), and space complexity is O(1) if using XOR, or O(26) if using a fixed-size frequency array.
