Write a C++ function `findAllPathsInMaze` that takes a square maze represented as a vector of vectors of integers (`m`), where `1` denotes a passable cell and `0` denotes a blocked cell, along with its dimension `n` (assumed consistent with the matrix size). The function must return a vector of strings, where each string represents a path from the top-left corner `(0,0)` to the bottom-right corner `(n-1, n-1)` using only moves 'D' (down), 'L' (left), 'R' (right), and 'U' (up). Paths must be in lexicographical order (D, L, R, U) as they would be generated by exploring moves in that order. The function should return an empty vector if the starting cell is blocked or if no path exists. Each cell can be visited at most once per path. Assume `n >= 1`.
#include <cassert>
#include <vector>
#include <string>

// using the function from above (declared here for completeness)
std::vector<std::string> findAllPathsInMaze(const std::vector<std::vector<int>>& m, int n);

int main() {
    // Test 1: Simple 2x2 fully open maze
    std::vector<std::vector<int>> m1 = {{1, 1}, {1, 1}};
    auto r1 = findAllPathsInMaze(m1, 2);
    assert(r1.size() == 2);
    assert(r1[0] == "DR" || r1[0] == "RD");
    assert(r1[1] == "DR" || r1[1] == "RD");
    assert(r1[0] != r1[1]);

    // Test 2: Blocked start -> empty
    std::vector<std::vector<int>> m2 = {{0, 1}, {1, 1}};
    assert(findAllPathsInMaze(m2, 2).empty());

    // Test 3: Blocked end -> empty
    std::vector<std::vector<int>> m3 = {{1, 1}, {1, 0}};
    assert(findAllPathsInMaze(m3, 2).empty());

    // Test 4: n=1, single cell open -> path is empty string
    std::vector<std::vector<int>> m4 = {{1}};
    auto r4 = findAllPathsInMaze(m4, 1);
    assert(r4.size() == 1);
    assert(r4[0] == "");

    // Test 5: 3x3 fully open, check number of paths (should be 12)
    std::vector<std::vector<int>> m5(3, std::vector<int>(3, 1));
    auto r5 = findAllPathsInMaze(m5, 3);
    assert(r5.size() == 12);

    // Test 6: Paths are lexicographically sorted when generated in D,L,R,U order
    for (size_t i = 0; i + 1 < r5.size(); ++i) {
        assert(r5[i] <= r5[i + 1]);
    }

    // Test 7: 3x3 with a central wall, only one path
    std::vector<std::vector<int>> m6 = {
        {1, 0, 1},
        {1, 0, 1},
        {1, 1, 1}
    };
    auto r6 = findAllPathsInMaze(m6, 3);
    assert(r6.size() == 1);
    assert(r6[0] == "DDDR");

    // Test 8: 2x2 with only right then down
    std::vector<std::vector<int>> m7 = {{1, 1}, {0, 1}};
    auto r7 = findAllPathsInMaze(m7, 2);
    assert(r7.size() == 1);
    assert(r7[0] == "RD");

    // Test 9: 2x2 with only down then right
    std::vector<std::vector<int>> m8 = {{1, 0}, {1, 1}};
    auto r8 = findAllPathsInMaze(m8, 2);
    assert(r8.size() == 1);
    assert(r8[0] == "DR");

    // Test 10: n=0 (edge case) -> empty
    std::vector<std::vector<int>> empty;
    assert(findAllPathsInMaze(empty, 0).empty());

    return 0;
}
#include <vector>
#include <string>
#include <functional>

// Find all paths from (0,0) to (n-1,n-1) in a maze of 1s and 0s.
// Moves: D, L, R, U. Output is lexicographically sorted by move order.
std::vector<std::string> findAllPathsInMaze(const std::vector<std::vector<int>>& m, int n) {
    std::vector<std::string> ans;
    if (n == 0 || m[0][0] == 0 || m[n-1][n-1] == 0) {
        return ans;
    }

    std::vector<std::vector<int>> visited(n, std::vector<int>(n, 0));
    std::string path;

    // Recursive lambda for backtracking
    std::function<void(int, int)> dfs = [&](int x, int y) {
        if (x == n - 1 && y == n - 1) {
            ans.push_back(path);
            return;
        }
        visited[x][y] = 1;

        // Move order: D, L, R, U for lexicographical order
        int dx[4] = {1, 0, 0, -1};
        int dy[4] = {0, -1, 1, 0};
        char dir[4] = {'D', 'L', 'R', 'U'};

        for (int i = 0; i < 4; ++i) {
            int nx = x + dx[i];
            int ny = y + dy[i];
            if (nx >= 0 && nx < n && ny >= 0 && ny < n &&
                m[nx][ny] == 1 && visited[nx][ny] == 0) {
                path.push_back(dir[i]);
                dfs(nx, ny);
                path.pop_back();
            }
        }

        visited[x][y] = 0;
    };

    dfs(0, 0);
    return ans;
}
// The problem is a classic backtracking search on a grid. The main function initializes a visited matrix (`pathcover`) of zeros, then starts the recursive `solve` from `(0,0)`. The base case triggers when the coordinate equals `(n-1, n-1)`, appending the current path string to the answer. Before recursing, the current cell is marked visited; after all four directional attempts, it is unmarked to allow other paths. The move order is deliberately D, L, R, U to match lexicographical ordering. The safety check in the given code has bugs (e.g., `y == 0 && y < n` should be `y >= 0 && y < n`, `m[x][y] = 1` is assignment not comparison), so the reference solution fixes these. Important edge cases: if the start is blocked, return empty; if `n=1` and start is unblocked, return `[""]` (empty path); if no moves are possible due to blocks or visited cells, backtrack. Time complexity is O(4^(n^2)) in the worst case for the number of paths, but in practice it's bounded by the number of distinct simple paths. Space complexity is O(n^2) for the visited matrix and recursion stack, plus O(path_length) for storing each path string.
