// Write a C++ function `steffensen` that, given a unary function `f` (of type `double (*)(double)` or any callable with a `double` argument and `double` return) and an initial guess `x0`, returns an `Eigen::VectorXd` containing all iterates generated by Steffensen's method until convergence. The method should terminate when the absolute difference between consecutive iterates is less than a tolerance of `1e-12`, and also stop if the denominator in the method is zero to avoid division by zero. The returned vector must include the initial guess as the first element, followed by every subsequent iterate until the stopping criterion is met. The function must be templated on the callable type, use `Eigen::VectorXd`, and should not allocate more memory than necessary (i.e., grow the vector incrementally). The function must handle edge cases such as an initial guess that already satisfies the convergence criterion (return a vector of size 1) or a zero denominator in the first iteration (stop immediately). Do not modify the input function or output any text.

#include <cassert>
#include <cmath>
#include <Eigen/Dense>

// Include the solution function here (for completeness, but in a real test it would be in a header)
// Assume the above steffensen template is defined before this main.

int main() {
    // Test 1: Simple root at x=1 for f(x)=x-1, initial guess 0
    auto f1 = [](double x) { return x - 1.0; };
    Eigen::VectorXd v1 = steffensen(f1, 0.0);
    assert(v1.size() > 0);
    assert(std::abs(v1(v1.size()-1) - 1.0) < 1e-10);
    // First iterate should be initial guess
    assert(std::abs(v1(0) - 0.0) < 1e-15);

    // Test 2: Known equation from snippet: x*exp(x)-1, root ~0.567143
    auto f2 = [](double x) { return x * std::exp(x) - 1.0; };
    Eigen::VectorXd v2 = steffensen(f2, 1.0);
    assert(v2(v2.size()-1) > 0.5 && v2(v2.size()-1) < 0.6);
    // Ensure monotonic decrease from initial guess
    assert(v2(0) == 1.0);

    // Test 3: Starting exactly at root
    auto f3 = [](double x) { return x - 3.0; };
    Eigen::VectorXd v3 = steffensen(f3, 3.0);
    assert(v3.size() == 1);
    assert(v3(0) == 3.0);

    // Test 4: Zero denominator (constant function) – should not divide by zero
    auto f4 = [](double x) { return 5.0; };
    Eigen::VectorXd v4 = steffensen(f4, 0.0);
    // Should stop immediately after initial guess (size 1) because fx0=5, x1=5, fx1=5, denominator=0
    assert(v4.size() == 1);
    assert(v4(0) == 0.0);

    // Test 5: Quadratic convergence check: ensure errors decrease rapidly
    auto f5 = [](double x) { return std::sin(x) - 0.5; }; // root around pi/6
    Eigen::VectorXd v5 = steffensen(f5, 0.0);
    assert(v5.size() > 2);
    double e1 = std::abs(v5(1) - (std::asin(0.5)));
    double e2 = std::abs(v5(2) - (std::asin(0.5)));
    // Error should decrease at least by a factor of 10 in the first two steps
    assert(e2 < e1 * 0.1);

    // Test 6: Negative initial guess
    auto f6 = [](double x) { return x * x - 4.0; }; // roots +-2
    Eigen::VectorXd v6 = steffensen(f6, -5.0);
    // Converges to -2
    assert(std::abs(v6(v6.size()-1) - (-2.0)) < 1e-10);
    assert(v6(0) == -5.0);

    return 0;
}

#include <Eigen/Dense>
#include <vector>
#include <cmath>
#include <limits>

/**
 * Steffensen's method for root finding.
 * @tparam Function Callable type with double(double) signature.
 * @param f Function to find root of.
 * @param x0 Initial guess.
 * @return Vector containing all iterates from x0 until convergence.
 */
template <class Function>
Eigen::VectorXd steffensen(const Function& f, double x0) {
    using std::abs;
    const double tol = 1e-12;
    std::vector<double> iterates;
    iterates.push_back(x0);

    double x_prev = x0;
    while (true) {
        double fx0 = f(x_prev);
        if (abs(fx0) < tol) {
            break; // Already at root
        }
        double x1 = x_prev + fx0;
        double fx1 = f(x1);
        double denominator = fx1 - fx0;
        if (abs(denominator) < std::numeric_limits<double>::epsilon()) {
            break; // Avoid division by zero
        }
        double x_new = x_prev - fx0 * (x1 - x_prev) / denominator;
        if (!std::isfinite(x_new)) {
            break; // Non-finite, stop
        }
        iterates.push_back(x_new);
        if (abs(x_new - x_prev) < tol) {
            break; // Converged
        }
        x_prev = x_new;
    }

    Eigen::VectorXd result(iterates.size());
    for (size_t i = 0; i < iterates.size(); ++i) {
        result(i) = iterates[i];
    }
    return result;
}

// Steffensen's method is a root-finding algorithm that accelerates the convergence of fixed-point iteration by using a two-step finite difference approximation of the derivative. Given a function `f` and an initial guess `x0`, the iteration is:
// 1. Compute `x1 = x0 + f(x0)`.
// 2. Compute `x2 = x1 + f(x1)`.
// 3. Compute the denominator `d = f(x1) - f(x0)`. If `|d|` is extremely small (e.g., less than `std::numeric_limits<double>::epsilon()`), stop to avoid division by zero. Otherwise, update:
//    `x_new = x0 - f(x0) * (x1 - x0) / d`.
// 4. Set `x0 = x_new` and repeat until `|x_new - x_old| < tol` (where `tol = 1e-12`). Also stop if the function value is nearly zero, as an extra safety.
//
// The algorithm requires storing all iterates, so we maintain a `std::vector<double>` and push each new iterate. After convergence, convert to an `Eigen::VectorXd` by copying. Time complexity: each iteration evaluates `f` twice (once for `x1` and once for `x2`), and typically converges quadratically for simple roots, so the number of iterations is small (often fewer than 10). Space complexity: `O(k)` where `k` is the number of iterates stored, plus constant extra space for temporary variables. Edge cases: if `f(x0)` is zero initially, then `x0` is already a root; we return a vector with one element. If at any point the denominator `d` becomes zero (e.g., `f` is constant), we should stop and return the current iterate list, because the next update is undefined. Also, for robustness, if the function returns non-finite values (NaN or inf), we should stop to avoid infinite loops.
