Write a standalone C++ function `shellSort(int arr[], int n)` that sorts an integer array in ascending order using the Shell sort algorithm with the gap sequence generated by repeatedly applying `h = 3 * h + 1` starting from 1 while `h < n/3` (then reversing by `h /= 3`). The function must operate in-place, handle arrays of any size `n >= 0` (including empty arrays), and use insertion sort logic within each gap pass. The function should be templated to work with any numeric type (e.g., `int`, `double`) and must not call any other sorting functions. You may include `<algorithm>` for `std::swap` if needed, but the core algorithm must be implemented manually. The task is to produce only the function definition (no `main`), and then verify it with test code that checks sorting correctness on arrays of varying sizes, including edge cases like single-element, empty, already sorted, reverse-sorted, and arrays with duplicates.
// The solution implements Shell sort by first computing the largest gap `h` such that `h < n/3` using the recurrence `h = 3*h + 1`, which yields gaps like 1, 4, 13, 40, ... (a well-known sequence with good practical performance). Then, for each decreasing `h` (dividing by 3 each outer iteration), the algorithm performs an insertion sort on subarrays formed by elements spaced `h` apart. Specifically, for each index `i` from `h` to `n-1`, it saves the element `e = arr[i]` and shifts larger elements at positions `i-h, i-2h, ...` to the right by `h` until the correct position is found. This is efficient because the array becomes more sorted with each pass. Important edge cases: if `n <= 1`, the function does nothing (the while loop for gap computation may compute an `h` but the inner loops handle empty or single-element arrays correctly because `i` starts at `h` which could be ≥ `n`); if `n == 0`, `n/3` is 0 and the while loop condition `h < 0` is false (since `h` starts at 1), so the outer `while` loop runs with `h=1`, but the inner loop `for i=1; i<0` doesn't execute, leaving the array unchanged. The time complexity is O(n^(3/2)) in the worst case for this gap sequence (empirically better on average), and O(n) best case when the array is nearly sorted. Space complexity is O(1) auxliary, as sorting is in-place.
#include <cstddef>  // for size_t (optional, not used directly)

// Shell sort: sorts arr[0..n-1] in ascending order using the 3*h+1 gap sequence.
template<typename T>
void shellSort(T arr[], int n) {
    // Compute initial gap: largest h such that h < n/3 using h = 3*h + 1
    int h = 1;
    while (h < n / 3) {
        h = 3 * h + 1;
    }

    // Reduce gap each pass
    while (h >= 1) {
        // h-sort: insertion sort on elements spaced by h
        for (int i = h; i < n; ++i) {
            T temp = arr[i];
            int j = i;
            // Shift elements at positions i-h, i-2h, ... to the right
            while (j >= h && arr[j - h] > temp) {
                arr[j] = arr[j - h];
                j -= h;
            }
            arr[j] = temp;
        }
        h /= 3;
    }
}
#include <cassert>
#include <algorithm>  // for std::is_sorted and std::reverse
#include <vector>

// The solution function (as defined above) is assumed to be available.
// To keep this standalone, we replicate the solution here (or include the header).
template<typename T>
void shellSort(T arr[], int n) {
    int h = 1;
    while (h < n / 3) h = 3 * h + 1;
    while (h >= 1) {
        for (int i = h; i < n; ++i) {
            T temp = arr[i];
            int j = i;
            while (j >= h && arr[j - h] > temp) {
                arr[j] = arr[j - h];
                j -= h;
            }
            arr[j] = temp;
        }
        h /= 3;
    }
}

int main() {
    // Test 1: Empty array
    int empty[] = {};
    shellSort(empty, 0);
    assert(std::is_sorted(empty, empty));

    // Test 2: Single element
    int single[] = {42};
    shellSort(single, 1);
    assert(single[0] == 42);

    // Test 3: Small array with duplicates
    int dup[] = {5, 3, 5, 1, 3};
    shellSort(dup, 5);
    assert(std::is_sorted(dup, dup + 5));
    assert(dup[0] == 1 && dup[4] == 5);

    // Test 4: Already sorted array
    int sorted[] = {1, 2, 3, 4, 5};
    shellSort(sorted, 5);
    assert(std::is_sorted(sorted, sorted + 5));

    // Test 5: Reverse sorted array
    int rev[] = {9, 8, 7, 6, 5, 4};
    shellSort(rev, 6);
    assert(std::is_sorted(rev, rev + 6));
    assert(rev[0] == 4 && rev[5] == 9);

    // Test 6: Larger array with random values (using fixed values for determinism)
    int large[] = {37, 12, 89, 5, 42, 17, 92, 3, 56, 81, 23, 64, 78, 9, 45};
    int n_large = sizeof(large) / sizeof(large[0]);
    shellSort(large, n_large);
    assert(std::is_sorted(large, large + n_large));

    // Test 7: Array size that produces multiple gap reductions (n=100)
    std::vector<int> vec(100);
    for (int i = 0; i < 100; ++i) vec[i] = (i * 73) % 100;  // deterministic pseudo-random
    shellSort(vec.data(), vec.size());
    assert(std::is_sorted(vec.begin(), vec.end()));

    // Test 8: All identical elements
    int same[] = {7, 7, 7, 7, 7};
    shellSort(same, 5);
    assert(std::is_sorted(same, same + 5));

    // Test 9: Negative numbers
    int neg[] = {-3, -10, 4, -1, 0, -2};
    shellSort(neg, 6);
    assert(std::is_sorted(neg, neg + 6));

    // Test 10: Double type (templated function)
    double dbl[] = {3.5, -1.2, 4.0, -0.5, 2.8};
    shellSort(dbl, 5);
    assert(std::is_sorted(dbl, dbl + 5));

    return 0;
}
