Write a C++ function `findKthSmallestPair` that takes an unsorted array of integers, its size `n`, and an integer `k` (1-indexed), and returns a `std::pair<int,int>` containing the two elements that form the k-th smallest ordered pair `(a, b)` where `a` is chosen from the array and `b` is chosen from the array, with the pair sorted in non-decreasing order and `a` must be ≤ `b`. The ordering of pairs is lexicographic: first compare the first elements, then the second. Note that duplicate values in the array are treated as distinct positions, and the same value can appear in both positions of the pair (i.e., `(x, x)` is allowed if `x` appears at least once, but for counting purposes each occurrence is distinct). For example, if the array is `[1, 3, 2]`, all possible ordered pairs sorted lexicographically are `(1,1), (1,2), (1,3), (2,2), (2,3), (3,3)` (but with duplicates counted accordingly). The function must work for any `1 ≤ k ≤ n*(n+1)/2`.

#include <cassert>
#include <vector>
#include <utility>

int main() {
    // Simple array
    std::vector<int> v1 = {1, 3, 2};
    assert(findKthSmallestPair(v1, 1) == std::make_pair(1, 1));
    assert(findKthSmallestPair(v1, 2) == std::make_pair(1, 2));
    assert(findKthSmallestPair(v1, 3) == std::make_pair(1, 3));
    assert(findKthSmallestPair(v1, 4) == std::make_pair(2, 2));
    assert(findKthSmallestPair(v1, 5) == std::make_pair(2, 3));
    assert(findKthSmallestPair(v1, 6) == std::make_pair(3, 3));

    // All identical
    std::vector<int> v2 = {5, 5, 5};
    assert(findKthSmallestPair(v2, 1) == std::make_pair(5, 5));
    assert(findKthSmallestPair(v2, 6) == std::make_pair(5, 5)); // only one unique pair, but positions count

    // Single element
    std::vector<int> v3 = {7};
    assert(findKthSmallestPair(v3, 1) == std::make_pair(7, 7));

    // Negative numbers
    std::vector<int> v4 = {-3, -1, -2};
    // Sorted: -3, -2, -1
    assert(findKthSmallestPair(v4, 1) == std::make_pair(-3, -3));
    assert(findKthSmallestPair(v4, 2) == std::make_pair(-3, -2));
    assert(findKthSmallestPair(v4, 3) == std::make_pair(-3, -1));
    assert(findKthSmallestPair(v4, 4) == std::make_pair(-2, -2));
    assert(findKthSmallestPair(v4, 5) == std::make_pair(-2, -1));
    assert(findKthSmallestPair(v4, 6) == std::make_pair(-1, -1));

    // Larger array with duplicates
    std::vector<int> v5 = {2, 2, 3, 3};
    assert(findKthSmallestPair(v5, 1) == std::make_pair(2, 2));
    assert(findKthSmallestPair(v5, 2) == std::make_pair(2, 2)); // positions count separately
    assert(findKthSmallestPair(v5, 3) == std::make_pair(2, 3));
    assert(findKthSmallestPair(v5, 4) == std::make_pair(2, 3));
    assert(findKthSmallestPair(v5, 5) == std::make_pair(3, 3));
    assert(findKthSmallestPair(v5, 6) == std::make_pair(3, 3));
    assert(findKthSmallestPair(v5, 7) == std::make_pair(3, 3));
    assert(findKthSmallestPair(v5, 8) == std::make_pair(3, 3));
    assert(findKthSmallestPair(v5, 9) == std::make_pair(3, 3));
    assert(findKthSmallestPair(v5, 10) == std::make_pair(3, 3));

    return 0;
}

#include <vector>
#include <algorithm>
#include <utility>

// Returns the k-th smallest pair (a, b) with a <= b from the given array.
// k is 1-indexed. Pairs are ordered lexicographically.
std::pair<int, int> findKthSmallestPair(const std::vector<int>& input, int k) {
    // Work on a sorted copy to keep the input const-correct.
    std::vector<int> arr = input;
    std::sort(arr.begin(), arr.end());
    
    int n = static_cast<int>(arr.size());
    
    // Iterate over possible first elements.
    for (int i = 0; i < n; ++i) {
        int blockSize = n - i;  // number of pairs starting with arr[i]
        if (k <= blockSize) {
            // The second element is at index i + k - 1 within the block.
            int secondIndex = i + k - 1;
            return std::make_pair(arr[i], arr[secondIndex]);
        }
        k -= blockSize;
    }
    
    // Should never reach here if k is valid.
    return std::make_pair(-1, -1);
}

// The core idea is that the k-th smallest pair can be found by first sorting the array. Once sorted, we can view all valid pairs `(a, b)` with `a ≤ b` as being generated by choosing an index `i` for the first element (0-based) and an index `j` with `j ≥ i` for the second element. The number of pairs starting with the value at index `i` is `(n - i)`, because we can pair that element with itself and all elements to its right. Since the array is sorted, all pairs beginning with a smaller value are lexicographically smaller than any pair beginning with a larger value. Therefore, we can iterate over `i` from 0 to `n-1`, maintaining a cumulative count of pairs consumed. For each starting index `i`, the block of `(n - i)` pairs shares the same first element. If `k` falls within this block, we know the first element is `arr[i]`. Then, within this block, the pairs are ordered by the second element, which is `arr[j]` for `j` from `i` to `n-1`. The second element is the one at offset `(k - 1)` within that block, because `k` is 1-indexed. So we can compute `secondIndex = i + (k - 1)` and return `{arr[i], arr[secondIndex]}`. If `k` is larger than the block size, subtract the block size from `k` and move to the next `i`. Edge cases include duplicates: since the array is sorted, identical values appear consecutively, and the pair generation naturally counts each distinct position separately, so the method works correctly. The time complexity is dominated by sorting, which is O(n log n), and the final scan is O(n). Space complexity is O(n) if we sort a copy (or O(1) auxiliary if we sort in place, but we should avoid mutating the input in a const-correct function, so we make a copy).
